import { BellRing, Check, Chrome, LockKeyhole, Mail, MessageCircle, Send, ShieldCheck, Smartphone, Sparkles } from "lucide-react";
import type { ScreenId } from "./flow";
import type { ScreenCtx } from "./OnboardingScreens";
import { PageShell, Pill, PrimaryButton, SectionCard, SecondaryButton, StatusRow } from "./ui";

const Footer = ({ ctx, primary = "Continue", onPrimary }: { ctx: ScreenCtx; primary?: string; onPrimary?: () => void }) => <div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={onPrimary ?? ctx.next} className="flex-1">{primary}</PrimaryButton></div>;

export function renderAgentSetupScreen(id: ScreenId, ctx: ScreenCtx) {
  if (id === "s14") return <PageShell eyebrow="ONECLICK AGENT" title="Turn your Career Passport into OneClick" description="OneClick uses a private application browser, your verified career information, and optional job-search email access to complete approved applications without repeatedly interrupting you." footer={<Footer ctx={ctx} primary="Set Up OneClick"/>}><div className="grid gap-4 sm:grid-cols-3"><SectionCard><Pill tone="green">READY</Pill><div className="mt-4 text-lg font-black">Career Passport</div><p className="mt-2 text-sm leading-6 text-gray-500">Verified identity, resume, preferences, and reusable answers.</p></SectionCard><SectionCard><Pill tone="yellow">SETUP</Pill><div className="mt-4 text-lg font-black">Application Browser</div><p className="mt-2 text-sm leading-6 text-gray-500">Private browser for employer forms, sessions, and human handoffs.</p></SectionCard><SectionCard><Pill tone="yellow">CONNECT</Pill><div className="mt-4 text-lg font-black">Job-Search Email</div><p className="mt-2 text-sm leading-6 text-gray-500">Read-only access for relevant verification and application messages.</p></SectionCard></div></PageShell>;

  if (id === "s15") return <PageShell eyebrow="PRIVATE BROWSER" title="Your private application browser" description="OneClick uses a secure browser dedicated to your applications so employer sessions and application progress can continue even when your laptop is closed." footer={<Footer ctx={ctx} primary="Activate Application Browser"/>}><SectionCard><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Chrome size={28}/></div><div><div className="text-lg font-black">Built for application continuity</div><div className="mt-3 space-y-3 text-sm leading-6 text-gray-600"><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>Employer sessions can persist between application steps.</div><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>Application work can continue while you leave the app.</div><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>When a genuine human step appears, control can be handed to you securely.</div></div></div></div></SectionCard></PageShell>;

  if (id === "s16") return <PageShell eyebrow="PRIVATE BROWSER" title="Your Application Browser is ready" description="OneClick can now open and work on applications you approve." footer={<Footer ctx={ctx} primary="Connect Job-Search Email"/>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#E9FFE9] text-[#0B6B22]"><Check size={30}/></div><div><Pill tone="green">ACTIVE</Pill><div className="mt-2 text-xl font-black">Private Application Browser</div></div></div><div className="mt-6"><StatusRow label="Secure application session" value="Ready"/><StatusRow label="Human handoff" value="Available"/><StatusRow label="Employer session continuity" value="Ready"/></div></SectionCard></PageShell>;

  if (id === "s17") return <PageShell eyebrow="EMAIL CONNECTION" title="Let OneClick handle application verification" description="Connect the Gmail account you use for job applications so OneClick can detect relevant verification and application messages while completing approved applications." footer={<Footer ctx={ctx} primary="Connect Gmail"/>}><SectionCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Mail size={24}/></div><div><div className="font-black">Read-only job-search email connection</div><div className="mt-1 text-xs text-gray-500">You choose which Gmail account to connect.</div></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#E9FFE9] p-4"><div className="text-sm font-black text-[#0B6B22]">OneClick can</div><div className="mt-3 space-y-2 text-sm text-gray-700"><div>✓ Detect relevant verification messages</div><div>✓ Detect application confirmations</div><div>✓ Surface application updates</div></div></div><div className="rounded-2xl bg-gray-50 p-4"><div className="text-sm font-black">OneClick cannot</div><div className="mt-3 space-y-2 text-sm text-gray-700"><div>✕ Send email</div><div>✕ Delete email</div><div>✕ Edit messages</div></div></div></div></SectionCard></PageShell>;

  if (id === "s18") return <PageShell eyebrow="GOOGLE" title="You’re continuing to Google" description="Google owns the permission screen. Apply Wizz never asks you to type your Google password into our app." footer={<Footer ctx={ctx} primary="Simulate Google Approval"/>}><SectionCard><div className="mx-auto max-w-md rounded-3xl border border-gray-200 p-6"><div className="text-center text-3xl font-black tracking-tight">Google</div><div className="mt-6 text-center font-black">Choose an account</div><button onClick={() => ctx.setState({ gmailConnected: true })} className="mt-5 flex min-h-16 w-full items-center gap-3 rounded-2xl border border-gray-200 px-4 text-left"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#2C76FF] font-black text-white">R</div><div><div className="font-bold">Ramakrishna Chanda</div><div className="text-xs text-gray-500">r••••••@gmail.com</div></div></button></div></SectionCard></PageShell>;

  if (id === "s19") return <PageShell eyebrow="EMAIL CONNECTION" title="Job-search email connected" description="OneClick can now use the connected mailbox for relevant application verification and status activity." footer={<Footer ctx={ctx}/>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#E9FFE9] text-[#0B6B22]"><Mail size={28}/></div><div><Pill tone="green">CONNECTED</Pill><div className="mt-2 text-xl font-black">r••••••@gmail.com</div></div></div><div className="mt-6"><StatusRow label="Application verification" value="Enabled"/><StatusRow label="Application confirmations" value="Enabled"/><StatusRow label="Application updates" value="Enabled"/></div></SectionCard></PageShell>;

  if (id === "s20") return <PageShell eyebrow="COMMUNICATIONS" title="How OneClick can reach you" description="OneClick stays quiet while automation works and uses your connected channels only when something meaningful needs you." footer={<div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => ctx.go(ctx.state.telegramConnected ? "s49" : "s48")} className="flex-1">Continue</PrimaryButton></div>}><div className="space-y-3"><SectionCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><BellRing size={22}/></div><div className="flex-1"><div className="font-black">Apply Wizz Push</div><div className="text-xs text-gray-500">Primary channel for actions and outcomes.</div></div><Pill tone="green">ON</Pill></div></SectionCard><SectionCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gray-100"><Smartphone size={22}/></div><div className="flex-1"><div className="font-black">SMS fallback</div><div className="text-xs text-gray-500">Used if an urgent action goes unanswered.</div></div><Pill tone="green">ON</Pill></div></SectionCard><button onClick={() => ctx.go("s48")} className="w-full text-left"><SectionCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EAF6FF] text-[#229ED9]"><Send size={22}/></div><div className="flex-1"><div className="font-black">Telegram</div><div className="text-xs text-gray-500">Optional direct-response channel for factual application questions.</div></div><Pill tone={ctx.state.telegramConnected ? "green" : "yellow"}>{ctx.state.telegramConnected ? "CONNECTED" : "CONNECT"}</Pill></div></SectionCard></button></div><SectionCard><div className="text-sm font-black">Attention Router</div><div className="mt-3 grid gap-2 text-sm text-gray-600"><div>In app → if you’re already active</div><div>Push → primary alert</div><div>Telegram → Yes / No / choice for normal factual questions</div><div>SMS → urgent fallback if there’s no response</div></div></SectionCard></PageShell>;

  if (id === "s48") return <PageShell eyebrow="TELEGRAM" title="Connect Telegram" description="Pair Telegram once so OneClick can send application-related attention requests and let you answer normal factual questions without reopening the app." footer={<div className="flex gap-3"><SecondaryButton onClick={() => ctx.go("s20")} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => { ctx.setState({ telegramConnected: true }); ctx.go("s49"); }} className="flex-1">Open Telegram</PrimaryButton></div>}><SectionCard><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-[#229ED9] text-white"><Send size={34}/></div><div className="mt-5 text-center"><div className="text-xl font-black">Pair with @ApplyWizzBot</div><p className="mt-2 text-sm leading-6 text-gray-500">We generate a one-time pairing link. You open Telegram, tap Start once, and this OneClick account becomes linked to that Telegram chat.</p></div><div className="mt-6"><StatusRow label="Application questions" value="Quick actions"/><StatusRow label="Submission outcomes" value="Allowed"/><StatusRow label="Sensitive answers" value="Stay in OneClick" positive={false}/></div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]">Telegram is optional. Disconnect it anytime from Connected Services.</div></PageShell>;

  if (id === "s49") return <PageShell eyebrow="TELEGRAM" title="Telegram connected" description="Your Apply Wizz bot channel is ready for application-related attention requests." footer={<div className="flex gap-3"><SecondaryButton onClick={() => { ctx.setState({ telegramConnected: false }); ctx.go("s20"); }} className="flex-1">Disconnect</SecondaryButton><PrimaryButton onClick={() => ctx.go("s50")} className="flex-1">See Quick Answer</PrimaryButton></div>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#EAF6FF] text-[#229ED9]"><Send size={28}/></div><div><Pill tone="green">CONNECTED</Pill><div className="mt-2 text-xl font-black">@rama_jobs</div></div></div><div className="mt-6"><StatusRow label="Factual Yes/No questions" value="Direct reply"/><StatusRow label="Application outcomes" value="Enabled"/><StatusRow label="Sensitive decisions" value="Secure app only" positive={false}/></div></SectionCard></PageShell>;

  if (id === "s50") return <PageShell eyebrow="TELEGRAM PREVIEW" title="Answer without reopening OneClick" description="Normal factual questions can be answered directly from Telegram. The application resumes immediately after your response." footer={<div className="flex gap-3"><SecondaryButton onClick={() => ctx.go("s49")} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => ctx.go("s51")} className="flex-1">Sensitive Example</PrimaryButton></div>}><div className="mx-auto max-w-sm rounded-[30px] bg-[#DCEBF2] p-4 shadow-sm"><div className="mb-4 text-center text-xs font-bold text-gray-500">Apply Wizz Bot</div><div className="rounded-2xl rounded-bl-md bg-white p-4 shadow-sm"><div className="text-xs font-black text-[#229ED9]">APPLY WIZZ NEEDS ONE ANSWER</div><div className="mt-2 font-black">Amazon — SDE Intern</div><div className="mt-3 text-sm leading-6">Are you currently bound by a non-compete agreement?</div>{ctx.state.telegramAnswer ? <div className="mt-4 rounded-xl bg-[#E9FFE9] p-3 text-sm font-bold text-[#0B6B22]">Answered: {ctx.state.telegramAnswer} — OneClick resumed your Amazon application.</div> : <div className="mt-4 grid gap-2">{(["Yes","No","I'm unsure"] as const).map((answer)=><button key={answer} onClick={() => ctx.setState({ telegramAnswer: answer })} className="min-h-11 rounded-xl bg-[#229ED9] px-4 font-bold text-white">{answer}</button>)}</div>}</div></div></PageShell>;

  if (id === "s51") return <PageShell eyebrow="SECURE ROUTING" title="Sensitive answers stay inside OneClick" description="Telegram can alert you that a decision is required, but it never exposes sensitive answer buttons in the message." footer={<div className="flex gap-3"><SecondaryButton onClick={() => ctx.go("s50")} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => ctx.go("s31")} className="flex-1">Review Securely</PrimaryButton></div>}><div className="mx-auto max-w-sm rounded-[30px] bg-[#DCEBF2] p-4 shadow-sm"><div className="mb-4 text-center text-xs font-bold text-gray-500">Apply Wizz Bot</div><div className="rounded-2xl rounded-bl-md bg-white p-4 shadow-sm"><div className="text-xs font-black text-[#FF5C5C]">YOUR DECISION IS REQUIRED</div><div className="mt-2 font-black">Microsoft — Software Engineer</div><div className="mt-3 text-sm leading-6">Microsoft has asked a sensitive application question.</div><button onClick={() => ctx.go("s31")} className="mt-4 min-h-11 w-full rounded-xl bg-[#0B1D33] px-4 font-bold text-white">Review securely in OneClick</button></div></div><div className="mt-4 rounded-2xl bg-[#FFF7CC] p-4 text-sm text-[#6E5900]"><ShieldCheck className="mr-2 inline" size={18}/>Sensitive decisions are never answered from Telegram.</div></PageShell>;

  if (id === "s21") return <PageShell eyebrow="ACTIVATED" title="Your Application Agent is ready" description="From now on, choose a job and approve the application. OneClick handles everything it safely can and interrupts you only for judgment, sensitive information, login, or genuine human verification." footer={<div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => ctx.go("s22")} className="flex-1">Go to Home</PrimaryButton></div>}><SectionCard><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-[#29FE29] text-[#0B1D33]"><Sparkles size={36}/></div><div className="mt-6 text-center"><div className="text-xl font-black">OneClick Agent Active</div><div className="mt-2 text-sm text-gray-500">Your setup is ready for the premium application workflow.</div></div><div className="mt-6"><StatusRow label="Career Passport" value="Ready"/><StatusRow label="Resume" value="Ready"/><StatusRow label="Application Browser" value="Active"/><StatusRow label="Job-search email" value={ctx.state.gmailConnected ? "Connected" : "Skipped"}/><StatusRow label="Push" value={ctx.state.pushEnabled ? "Active" : "Off"}/><StatusRow label="Telegram" value={ctx.state.telegramConnected ? "Connected" : "Optional"}/></div></SectionCard><div className="rounded-2xl bg-[#0B1D33] p-5 text-center text-white"><div className="text-sm font-extrabold text-[#29FE29]">ONECLICK PROMISE</div><div className="mt-2 text-lg font-black">Before Apply, remove uncertainty.<br/>After Apply, remove work.</div></div></PageShell>;

  return null;
}
