import { BellRing, Check, Chrome, LockKeyhole, Mail, MessageSquareText, ShieldCheck, Smartphone, Sparkles } from "lucide-react";
import type { ScreenId } from "./flow";
import type { ScreenCtx } from "./OnboardingScreens";
import { PageShell, Pill, PrimaryButton, ProgressBar, SectionCard, SecondaryButton, StatusRow, ToggleRow } from "./ui";

const Footer = ({ ctx, primary = "Continue" }: { ctx: ScreenCtx; primary?: string }) => <div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={ctx.next} className="flex-1">{primary}</PrimaryButton></div>;

export function renderAgentSetupScreen(id: ScreenId, ctx: ScreenCtx) {
  if (id === "s14") return <PageShell eyebrow="ONECLICK AGENT" title="Turn your Career Passport into OneClick" description="OneClick uses a private application browser, your verified career information, and optional job-search email access to complete approved applications without repeatedly interrupting you." footer={<Footer ctx={ctx} primary="Set Up OneClick"/>}><div className="grid gap-4 sm:grid-cols-3"><SectionCard><Pill tone="green">READY</Pill><div className="mt-4 text-lg font-black">Career Passport</div><p className="mt-2 text-sm leading-6 text-gray-500">Verified identity, resume, preferences, and reusable answers.</p></SectionCard><SectionCard><Pill tone="yellow">SETUP</Pill><div className="mt-4 text-lg font-black">Application Browser</div><p className="mt-2 text-sm leading-6 text-gray-500">Private browser for employer forms, sessions, and human handoffs.</p></SectionCard><SectionCard><Pill tone="yellow">CONNECT</Pill><div className="mt-4 text-lg font-black">Job-Search Email</div><p className="mt-2 text-sm leading-6 text-gray-500">Read-only access for relevant verification and application messages.</p></SectionCard></div></PageShell>;

  if (id === "s15") return <PageShell eyebrow="PRIVATE BROWSER" title="Your private application browser" description="OneClick uses a secure browser dedicated to your applications so employer sessions and application progress can continue even when your laptop is closed." footer={<Footer ctx={ctx} primary="Activate Application Browser"/>}><SectionCard><div className="flex items-start gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Chrome size={28}/></div><div><div className="text-lg font-black">Built for application continuity</div><div className="mt-3 space-y-3 text-sm leading-6 text-gray-600"><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>Employer sessions can persist between application steps.</div><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>Application work can continue while you leave the app.</div><div className="flex gap-2"><Check className="mt-1 shrink-0 text-[#0B6B22]" size={16}/>When a genuine human step appears, control can be handed to you securely.</div></div></div></div></SectionCard><div className="rounded-2xl bg-[#0B1D33] p-4 text-sm leading-6 text-white"><LockKeyhole className="mr-2 inline" size={18}/>Prototype note: this screen simulates activation only. No real browser automation is running in this frontend mockup.</div></PageShell>;

  if (id === "s16") return <PageShell eyebrow="PRIVATE BROWSER" title="Your Application Browser is ready" description="OneClick can now open and work on applications you approve." footer={<PrimaryButton onClick={ctx.next} className="w-full">Connect Job-Search Email</PrimaryButton>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#E9FFE9] text-[#0B6B22]"><Check size={30}/></div><div><Pill tone="green">ACTIVE</Pill><div className="mt-2 text-xl font-black">Private Application Browser</div></div></div><div className="mt-6"><StatusRow label="Secure application session" value="Ready"/><StatusRow label="Human handoff" value="Available"/><StatusRow label="Employer session continuity" value="Ready"/></div></SectionCard></PageShell>;

  if (id === "s17") return <PageShell eyebrow="EMAIL CONNECTION" title="Let OneClick handle application verification" description="Connect the Gmail account you use for job applications so OneClick can detect relevant verification and application messages while completing approved applications." footer={<div className="grid gap-3 sm:grid-cols-2"><SecondaryButton onClick={ctx.back}>Back</SecondaryButton><PrimaryButton onClick={ctx.next}>Connect Gmail</PrimaryButton></div>}><SectionCard><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Mail size={24}/></div><div><div className="font-black">Read-only job-search email connection</div><div className="mt-1 text-xs text-gray-500">You choose which Gmail account to connect.</div></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[#E9FFE9] p-4"><div className="text-sm font-black text-[#0B6B22]">OneClick can</div><div className="mt-3 space-y-2 text-sm text-gray-700"><div>✓ Detect relevant verification messages</div><div>✓ Detect application confirmations</div><div>✓ Surface application updates</div></div></div><div className="rounded-2xl bg-gray-50 p-4"><div className="text-sm font-black">OneClick cannot</div><div className="mt-3 space-y-2 text-sm text-gray-700"><div>✕ Send email</div><div>✕ Delete email</div><div>✕ Edit messages</div></div></div></div></SectionCard><button onClick={ctx.next} className="w-full text-center text-sm font-bold text-gray-500 underline underline-offset-4">Skip for now</button><p className="text-center text-xs leading-5 text-gray-400">If you skip, some employer verification steps may require you to provide the code yourself.</p></PageShell>;

  if (id === "s18") return <PageShell eyebrow="GOOGLE" title="You’re continuing to Google" description="Google owns the permission screen. Apply Wizz never asks you to type your Google password into our app." footer={<Footer ctx={ctx} primary="Simulate Google Approval"/>}><SectionCard><div className="mx-auto max-w-md rounded-3xl border border-gray-200 p-6"><div className="text-center text-3xl font-black tracking-tight">Google</div><div className="mt-6 text-center font-black">Choose an account</div><button className="mt-5 flex min-h-16 w-full items-center gap-3 rounded-2xl border border-gray-200 px-4 text-left"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#2C76FF] font-black text-white">R</div><div><div className="font-bold">Ramakrishna Chanda</div><div className="text-xs text-gray-500">r••••••@gmail.com</div></div></button></div></SectionCard></PageShell>;

  if (id === "s19") return <PageShell eyebrow="EMAIL CONNECTION" title="Job-search email connected" description="OneClick can now use the connected mailbox for relevant application verification and status activity." footer={<Footer ctx={ctx}/>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#E9FFE9] text-[#0B6B22]"><Mail size={28}/></div><div><Pill tone="green">CONNECTED</Pill><div className="mt-2 text-xl font-black">r••••••@gmail.com</div></div></div><div className="mt-6"><StatusRow label="Application verification" value="Enabled"/><StatusRow label="Application confirmations" value="Enabled"/><StatusRow label="Application updates" value="Enabled"/></div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm leading-6 text-[#185BCC]"><ShieldCheck className="mr-2 inline" size={18}/>Your email connection is separate from account sign-in and can be disconnected later.</div></PageShell>;

  if (id === "s20") return <PageShell eyebrow="NOTIFICATIONS" title="Stay reachable when OneClick needs you" description="Most applications should not need you. When one does, the interruption should be fast, clear, and worth your attention." footer={<Footer ctx={ctx} primary="Enable Notifications"/>}><div className="space-y-3"><ToggleRow title="Apply Wizz Push" description="Recommended. Human verification, new questions, failures, submissions, and interview activity." defaultOn/><ToggleRow title="SMS fallback" description="Use your verified phone when a high-priority push cannot reach you." defaultOn/><ToggleRow title="Low-priority activity" description="Keep normal automation activity inside the app rather than sending noisy alerts." defaultOn={false}/></div><SectionCard><div className="flex items-start gap-3"><BellRing size={22} className="mt-1 text-[#2C76FF]"/><div><div className="font-black">Example notification</div><div className="mt-2 rounded-2xl bg-gray-50 p-4 text-sm"><div className="font-bold">Apply Wizz</div><div className="mt-1">NVIDIA needs human verification. Usually takes under a minute.</div></div></div></div></SectionCard></PageShell>;

  if (id === "s21") return <PageShell eyebrow="ACTIVATED" title="Your Application Agent is ready" description="From now on, choose a job and approve the application. OneClick handles everything it safely can and interrupts you only for judgment, sensitive information, login, or genuine human verification." footer={<PrimaryButton onClick={() => ctx.go("s22")} className="w-full">Go to Home</PrimaryButton>}><SectionCard><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-[#29FE29] text-[#0B1D33]"><Sparkles size={36}/></div><div className="mt-6 text-center"><div className="text-xl font-black">OneClick Agent Active</div><div className="mt-2 text-sm text-gray-500">Your setup is ready for the premium application workflow.</div></div><div className="mt-6"><StatusRow label="Career Passport" value="Ready"/><StatusRow label="Resume" value="Ready"/><StatusRow label="Reusable answers" value="Ready"/><StatusRow label="Application Browser" value="Active"/><StatusRow label="Job-search email" value="Connected"/><StatusRow label="Notifications" value="Active"/></div></SectionCard><div className="rounded-2xl bg-[#0B1D33] p-5 text-center text-white"><div className="text-sm font-extrabold text-[#29FE29]">ONECLICK PROMISE</div><div className="mt-2 text-lg font-black">Before Apply, remove uncertainty.<br/>After Apply, remove work.</div></div></PageShell>;

  return null;
}
