import { AlertTriangle, Check, Clock3, KeyRound, LockKeyhole, MailCheck, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import type { ScreenId } from "./flow";
import type { ScreenCtx } from "./OnboardingScreens";
import { Metric, PageShell, Pill, PrimaryButton, ProgressBar, SectionCard, SecondaryButton, StatusRow } from "./ui";

const Footer = ({ ctx, primary = "Continue" }: { ctx: ScreenCtx; primary?: string }) => <div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={ctx.next} className="flex-1">{primary}</PrimaryButton></div>;

export function renderExecutionScreen(id: ScreenId, ctx: ScreenCtx) {
  if (id === "s29") return <PageShell eyebrow="APPLICATION IN PROGRESS" title="OneClick is applying" description="Microsoft · Software Engineer. You can leave this screen—OneClick will notify you only if something genuinely needs your attention." footer={<div className="grid gap-3 sm:grid-cols-2"><PrimaryButton onClick={() => ctx.go("s22")}>Back to Home</PrimaryButton><SecondaryButton onClick={() => ctx.go("s30")}>Preview interruption states</SecondaryButton></div>}><SectionCard><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Sparkles size={26}/></div><div className="flex-1"><div className="font-black">Application in progress</div><div className="mt-1 text-xs text-gray-500">OneClick is completing the employer workflow.</div></div><Pill tone="blue">RUNNING</Pill></div><div className="mt-6"><ProgressBar value={68}/></div><div className="mt-6"><StatusRow label="Application opened" value="Done"/><StatusRow label="Profile information added" value="Done"/><StatusRow label="Resume uploaded" value="Done"/><StatusRow label="Questions" value="Completing" positive={false}/><StatusRow label="Verification" value="Waiting" positive={false}/><StatusRow label="Submission" value="Waiting" positive={false}/></div></SectionCard><div className="rounded-2xl bg-[#0B1D33] p-4 text-sm leading-6 text-white"><Clock3 className="mr-2 inline" size={17}/>The premium experience is backgroundable. Normal automation should never require the candidate to watch a progress screen.</div></PageShell>;

  if (id === "s30") return <PageShell eyebrow="ACTION NEEDED" title="OneClick needs one answer" description="Microsoft asks one factual question we have not seen before. Answer it here and OneClick immediately resumes the application." footer={<Footer ctx={ctx} primary="Continue Application"/>}><SectionCard><div className="text-xs font-black uppercase tracking-wide text-[#2C76FF]">Microsoft asks</div><div className="mt-3 text-xl font-black">Are you currently bound by a non-compete agreement?</div><div className="mt-5 grid gap-2 sm:grid-cols-3">{["Yes","No","I’m unsure"].map((x)=><SecondaryButton key={x}>{x}</SecondaryButton>)}</div></SectionCard><label className="flex items-center gap-3 rounded-2xl bg-[#EFFBFF] p-4 text-sm font-bold text-[#185BCC]"><input type="checkbox" defaultChecked className="h-5 w-5"/>Remember my answer for future applications when appropriate</label></PageShell>;

  if (id === "s31") return <PageShell eyebrow="SENSITIVE QUESTION" title="Your decision is required" description="This answer is sensitive, so OneClick will never choose it for you." footer={<Footer ctx={ctx} primary="Save & Resume"/>}><SectionCard className="border-yellow-200 bg-[#FFFDF2]"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 shrink-0 text-[#6E5900]" size={22}/><div><div className="text-xs font-black uppercase tracking-wide text-[#6E5900]">Microsoft asks</div><div className="mt-2 text-lg font-black">Do you wish to self-identify as having a disability?</div><p className="mt-3 text-sm leading-6 text-gray-600">The choices shown here are simulated employer-form options. OneClick does not infer, recommend, or silently reuse this type of answer.</p></div></div><div className="mt-5 grid gap-2">{["Yes","No","I do not wish to answer"].map((x)=><SecondaryButton key={x}>{x}</SecondaryButton>)}</div></SectionCard></PageShell>;

  if (id === "s32") return <PageShell eyebrow="HUMAN STEP" title="Microsoft needs human verification" description="OneClick paused safely at a step that requires a real person. Complete it in your secure application session and the agent will resume automatically." footer={<div className="grid gap-3 sm:grid-cols-2"><SecondaryButton onClick={ctx.back}>Remind Me Later</SecondaryButton><PrimaryButton onClick={ctx.next}>Complete Verification</PrimaryButton></div>}><SectionCard><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-[#FFF7CC] text-[#6E5900]"><AlertTriangle size={34}/></div><div className="mt-5 text-center"><div className="text-xl font-black">Usually under 1 minute</div><div className="mt-2 text-sm text-gray-500">Your application remains paused safely until you finish this one step.</div></div></SectionCard></PageShell>;

  if (id === "s33") return <PageShell eyebrow="PRIVATE BROWSER" title="Secure Application Session" description="You’re temporarily controlling your private application browser. Complete the required employer verification, then hand control back to OneClick." footer={<Footer ctx={ctx} primary="Done — Resume OneClick"/>}><SectionCard className="overflow-hidden p-0"><div className="flex items-center gap-2 border-b border-gray-200 bg-gray-50 px-4 py-3"><span className="h-3 w-3 rounded-full bg-[#FF5C5C]"/><span className="h-3 w-3 rounded-full bg-[#FFDE59]"/><span className="h-3 w-3 rounded-full bg-[#29FE29]"/><div className="ml-2 flex-1 truncate rounded-xl bg-white px-3 py-2 text-xs text-gray-400">careers.microsoft.com/application/verify</div></div><div className="p-5"><div className="rounded-2xl border border-dashed border-gray-300 bg-gray-50 p-8 text-center"><LockKeyhole className="mx-auto text-[#2C76FF]" size={30}/><div className="mt-4 font-black">Employer human-verification area</div><p className="mt-2 text-sm leading-6 text-gray-500">This frontend mockup represents the secure browser handoff. It does not bypass or solve a real verification challenge.</p></div></div></SectionCard></PageShell>;

  if (id === "s34") return <PageShell eyebrow="SIGN IN" title="Microsoft needs you to sign in once" description="Enter employer credentials directly inside your secure application session. OneClick does not ask you to paste your password into an Apply Wizz profile field." footer={<Footer ctx={ctx} primary="Simulate Successful Sign In"/>}><SectionCard><div className="flex items-start gap-3"><KeyRound className="mt-1 text-[#2C76FF]" size={22}/><div><div className="font-black">Employer login</div><p className="mt-2 text-sm leading-6 text-gray-500">In production, this would be the employer-owned login page inside your private application browser.</p></div></div><div className="mt-5 grid gap-3"><input placeholder="Employer email" defaultValue="rama@example.com" className="min-h-12 rounded-2xl border border-gray-200 px-4 text-sm"/><input type="password" placeholder="Employer password" defaultValue="demopassword" className="min-h-12 rounded-2xl border border-gray-200 px-4 text-sm"/></div></SectionCard></PageShell>;

  if (id === "s35") return <PageShell eyebrow="RECOVERY" title="We couldn’t finish this application" description="OneClick explains recoverable problems in consumer language and keeps manual completion as a genuine fallback—not the normal workflow." footer={<div className="grid gap-3 sm:grid-cols-2"><SecondaryButton onClick={() => ctx.go("s22")}>Back to Home</SecondaryButton><PrimaryButton onClick={ctx.next}>Try Again</PrimaryButton></div>}><SectionCard><div className="flex gap-3"><AlertTriangle className="mt-1 shrink-0 text-[#FF5C5C]"/><div><div className="font-black">Employer site changed during the application</div><div className="mt-2 text-sm leading-6 text-gray-500">OneClick paused before submitting because a required employer step changed unexpectedly.</div></div></div><div className="mt-5"><StatusRow label="Career Passport" value="Safe"/><StatusRow label="Application data" value="Saved"/><StatusRow label="Employer submission" value="Not submitted" positive={false}/></div></SectionCard><div className="grid gap-3 sm:grid-cols-3"><SecondaryButton><RotateCcw className="mr-1 inline" size={16}/>Retry</SecondaryButton><SecondaryButton>Complete Missing Step</SecondaryButton><SecondaryButton>Complete Manually</SecondaryButton></div></PageShell>;

  if (id === "s36") return <PageShell eyebrow="SUBMITTED" title="Application submitted" description="Microsoft · Software Engineer · submitted today at 11:42 PM." footer={<div className="grid gap-3 sm:grid-cols-2"><SecondaryButton onClick={() => ctx.go("s22")}>Back Home</SecondaryButton><PrimaryButton onClick={() => ctx.go("s38")}>View Application</PrimaryButton></div>}><SectionCard><div className="mx-auto grid h-20 w-20 place-items-center rounded-[28px] bg-[#29FE29] text-[#0B1D33]"><Check size={36}/></div><div className="mt-5 text-center"><div className="text-2xl font-black">Done without busywork</div><div className="mt-2 text-sm text-gray-500">Your application is now tracked inside OneClick.</div></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric value="10" label="questions completed"/><Metric value="1" label="resume uploaded"/><Metric value="1" label="email verification"/><Metric value="0" label="interruptions"/></div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm leading-6 text-[#185BCC]"><MailCheck className="mr-2 inline" size={18}/>Email verification was handled automatically because the relevant job-search Gmail account was connected.</div></PageShell>;

  return null;
}
