import { AlertTriangle, BellRing, BriefcaseBusiness, Check, ChevronRight, FileText, HelpCircle, Laptop, LockKeyhole, Mail, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import type { ScreenId } from "./flow";
import type { ScreenCtx } from "./OnboardingScreens";
import { AppShell, Metric, PageShell, Pill, PrimaryButton, ProgressBar, SectionCard, SecondaryButton, StatusRow, ToggleRow } from "./ui";

const memory = [
  ["Relocation", "Yes", "Used 8 times", "Career Passport"],
  ["Earliest Start Date", "June 15, 2027", "Used 5 times", "Microsoft application"],
  ["Requires Sponsorship", "Yes", "Used 11 times", "Work Authorization"],
  ["Desired Compensation", "$140K+", "Used 3 times", "Job Preferences"],
];

function Signed({ id, ctx, children }: { id: ScreenId; ctx: ScreenCtx; children: React.ReactNode }) {
  return <AppShell current={id} go={ctx.go}>{children}</AppShell>;
}

function Timeline() {
  const events = [
    ["11:36 PM", "Application approved", "You authorized OneClick for Microsoft — Software Engineer."],
    ["11:37 PM", "Employer application opened", "Private application browser started the employer flow."],
    ["11:38 PM", "Career Passport added", "Verified profile details were reused."],
    ["11:39 PM", "Resume uploaded", "Software Engineering Resume.pdf"],
    ["11:40 PM", "10 questions completed", "8 reused answers + 2 answers you confirmed."],
    ["11:41 PM", "Email verification completed", "Handled automatically from your connected job-search email."],
    ["11:42 PM", "Application submitted", "Confirmation captured and application moved to Submitted."],
  ];
  return <div className="relative ml-2 border-l border-gray-200 pl-6">{events.map(([time,title,detail])=><div key={time} className="relative pb-7 last:pb-0"><div className="absolute -left-[31px] top-1 h-4 w-4 rounded-full border-2 border-white bg-[#29FE29]"/><div className="text-xs font-bold text-gray-400">{time}</div><div className="mt-1 font-black">{title}</div><div className="mt-1 text-sm leading-5 text-gray-500">{detail}</div></div>)}</div>;
}

export function renderManagementScreen(id: ScreenId, ctx: ScreenCtx) {
  if (id === "s37") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="blue">APPLICATIONS</Pill><h1 className="mt-4 text-3xl font-black">Your applications</h1><p className="mt-2 text-sm text-gray-500">Track everything OneClick is doing, what needs you, and what employers do next.</p><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{["All","Needs Attention","Applying","Submitted","Interviews","Offers","Closed"].map((x,i)=><button key={x} className={`min-h-10 shrink-0 rounded-full px-4 text-xs font-extrabold ${i===0?"bg-[#0B1D33] text-white":"border border-gray-200 bg-white text-gray-600"}`}>{x}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><SectionCard><button onClick={() => ctx.go("s38")} className="w-full text-left"><div className="flex justify-between gap-3"><div><div className="text-xs font-black text-[#2C76FF]">MICROSOFT</div><div className="mt-1 text-lg font-black">Software Engineer</div><div className="mt-1 text-xs text-gray-500">Redmond, WA</div></div><Pill tone="green">SUBMITTED</Pill></div><div className="mt-4 text-xs text-gray-500">Submitted today · 11:42 PM · 0 interruptions</div></button></SectionCard><SectionCard><button onClick={() => ctx.go("s32")} className="w-full text-left"><div className="flex justify-between gap-3"><div><div className="text-xs font-black text-[#2C76FF]">NVIDIA</div><div className="mt-1 text-lg font-black">ML Engineer</div><div className="mt-1 text-xs text-gray-500">Santa Clara, CA</div></div><Pill tone="yellow">NEEDS VERIFICATION</Pill></div><div className="mt-4 text-xs text-gray-500">Usually under 1 minute</div></button></SectionCard><SectionCard><button onClick={() => ctx.go("s30")} className="w-full text-left"><div className="flex justify-between gap-3"><div><div className="text-xs font-black text-[#2C76FF]">AMAZON</div><div className="mt-1 text-lg font-black">SDE Intern</div><div className="mt-1 text-xs text-gray-500">Seattle, WA</div></div><Pill tone="yellow">1 ANSWER</Pill></div><div className="mt-4 text-xs text-gray-500">OneClick is paused safely.</div></button></SectionCard><SectionCard><button onClick={() => ctx.go("s38")} className="w-full text-left"><div className="flex justify-between gap-3"><div><div className="text-xs font-black text-[#2C76FF]">GOOGLE</div><div className="mt-1 text-lg font-black">Software Engineer</div><div className="mt-1 text-xs text-gray-500">Mountain View, CA</div></div><Pill tone="green">SUBMITTED</Pill></div><div className="mt-4 text-xs text-gray-500">Submitted 18 minutes ago</div></button></SectionCard></div></div></Signed>;

  if (id === "s38") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><button onClick={() => ctx.go("s37")} className="mb-5 text-sm font-bold text-gray-500">← Applications</button><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><SectionCard><Pill tone="green">SUBMITTED</Pill><div className="mt-4 text-xs font-black text-[#2C76FF]">MICROSOFT</div><h1 className="mt-1 text-2xl font-black">Software Engineer</h1><div className="mt-2 text-sm text-gray-500">Redmond, WA · $140K–$175K</div><div className="mt-6 grid grid-cols-2 gap-3"><Metric value="10" label="questions"/><Metric value="0" label="interruptions"/></div><div className="mt-5"><StatusRow label="Resume" value="Uploaded"/><StatusRow label="Email verification" value="Automatic"/><StatusRow label="Submission receipt" value="Captured"/></div></SectionCard><SectionCard><div className="mb-6 text-lg font-black">Application Timeline</div><Timeline/></SectionCard></div></div></Signed>;

  if (id === "s39") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="red">ATTENTION CENTER</Pill><h1 className="mt-4 text-3xl font-black">Needs your attention</h1><p className="mt-2 text-sm text-gray-500">Only tasks software should not decide for you appear here.</p><div className="mt-6 space-y-4"><SectionCard><button onClick={() => ctx.go("s32")} className="flex w-full items-center gap-4 text-left"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#FFF7CC] text-[#6E5900]"><AlertTriangle size={22}/></div><div className="flex-1"><div className="font-black">NVIDIA · Human verification</div><div className="mt-1 text-sm text-gray-500">Usually under 1 minute · application paused safely</div></div><ChevronRight size={20}/></button></SectionCard><SectionCard><button onClick={() => ctx.go("s30")} className="flex w-full items-center gap-4 text-left"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Sparkles size={22}/></div><div className="flex-1"><div className="font-black">Amazon · One new question</div><div className="mt-1 text-sm text-gray-500">About 10 seconds · answer once, then OneClick resumes</div></div><ChevronRight size={20}/></button></SectionCard><SectionCard><button onClick={() => ctx.go("s34")} className="flex w-full items-center gap-4 text-left"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gray-100"><LockKeyhole size={22}/></div><div className="flex-1"><div className="font-black">Meta · Employer login expired</div><div className="mt-1 text-sm text-gray-500">Sign in once inside your private application browser</div></div><ChevronRight size={20}/></button></SectionCard></div></div></Signed>;

  if (id === "s40") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Pill tone="blue">CAREER PASSPORT</Pill><h1 className="mt-4 text-3xl font-black">Ramakrishna Chanda</h1><p className="mt-2 text-sm text-gray-500">Your durable professional identity for approved applications.</p></div><div className="min-w-48 rounded-2xl bg-white p-4 shadow-sm"><div className="flex justify-between text-sm font-bold"><span>Completeness</span><span>96%</span></div><div className="mt-3"><ProgressBar value={96}/></div></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{[["Personal Information","Ramakrishna Chanda · Dallas, TX"],["Education","MS Computer Science · May 2027"],["Experience","Software Engineer Intern · Acme Labs"],["Skills","React · Python · AWS · Machine Learning"],["Work Authorization","Authorized · Sponsorship required"],["Job Preferences","SWE / ML · Remote or Hybrid"],["Application Answers","18 reusable answers"],["Documents","Software Engineering Resume.pdf"]].map(([title,detail])=><SectionCard key={title}><div className="flex justify-between gap-3"><div><div className="font-black">{title}</div><div className="mt-2 text-sm leading-5 text-gray-500">{detail}</div><div className="mt-3 text-xs font-bold text-gray-400">Used in 14 applications</div></div><button className="text-xs font-bold text-[#2C76FF]">Edit</button></div></SectionCard>)}</div></div></Signed>;

  if (id === "s41") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="blue">ANSWER MEMORY</Pill><h1 className="mt-4 text-3xl font-black">What OneClick remembers</h1><p className="mt-2 text-sm text-gray-500">See the source, last confirmation, and reuse count for durable answers.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{memory.map(([label,value,used,source],i)=><SectionCard key={label}><button onClick={() => i===2 && ctx.go("s42")} className="w-full text-left"><div className="text-xs font-bold uppercase tracking-wide text-gray-400">{label}</div><div className="mt-2 text-2xl font-black">{value}</div><div className="mt-4 flex items-center justify-between text-xs text-gray-500"><span>{source}</span><Pill tone="green">{used}</Pill></div>{i===2 && <div className="mt-4 text-xs font-bold text-[#2C76FF]">Edit answer →</div>}</button></SectionCard>)}</div></div></Signed>;

  if (id === "s42") return <PageShell eyebrow="CHANGE PROTECTION" title="This answer changed" description="Important answer changes affect future applications only. OneClick never silently rewrites an application that was already submitted." footer={<div className="grid gap-3 sm:grid-cols-2"><SecondaryButton onClick={ctx.back}>Cancel</SecondaryButton><PrimaryButton onClick={() => ctx.go("s41")}>Update Future Applications</PrimaryButton></div>}><SectionCard><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-gray-50 p-4"><div className="text-xs font-bold text-gray-400">PREVIOUSLY</div><div className="mt-2 text-2xl font-black">No</div></div><div className="rounded-2xl bg-[#EFFBFF] p-4"><div className="text-xs font-bold text-[#185BCC]">NOW</div><div className="mt-2 text-2xl font-black">Yes</div></div></div><div className="mt-5 font-black">Requires Sponsorship</div><p className="mt-2 text-sm leading-6 text-gray-500">This answer was previously used in 6 applications. Updating it changes future applications only.</p></SectionCard></PageShell>;

  if (id === "s43") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="blue">DOCUMENTS</Pill><h1 className="mt-4 text-3xl font-black">Application documents</h1><p className="mt-2 text-sm text-gray-500">Manage reusable resumes, letters, transcripts, and portfolio documents.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{[["Software Engineering Resume.pdf","Primary resume · used in 12 applications"],["ML Resume.pdf","Alternative resume · used in 4 applications"],["Cover Letter — General.docx","Cover letter · used in 2 applications"],["UTD Transcript.pdf","Transcript · not used yet"],["Portfolio.pdf","Portfolio · used in 1 application"]].map(([title,detail],i)=><SectionCard key={title}><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#EFFBFF] text-[#2C76FF]"><FileText size={20}/></div><div className="flex-1"><div className="font-black">{title}</div><div className="mt-1 text-xs text-gray-500">{detail}</div>{i===0 && <div className="mt-3"><Pill tone="green">PRIMARY</Pill></div>}</div></div></SectionCard>)}</div><PrimaryButton className="mt-5">Upload Document</PrimaryButton></div></Signed>;

  if (id === "s44") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="blue">CONNECTIONS</Pill><h1 className="mt-4 text-3xl font-black">Connected services</h1><p className="mt-2 text-sm text-gray-500">These are the tools OneClick can use when you approve applications.</p><div className="mt-6 space-y-4"><SectionCard><StatusRow label="Application Browser" value="Active"/><p className="text-xs text-gray-500">Private application session ready for employer workflows and human handoffs.</p></SectionCard><SectionCard><StatusRow label="Job-Search Gmail" value="Connected"/><p className="text-xs text-gray-500">r••••••@gmail.com · read-only application verification and updates.</p></SectionCard><SectionCard><StatusRow label="Phone" value="Verified"/><p className="text-xs text-gray-500">+1 ••• ••• 0142 · SMS fallback available.</p></SectionCard><SectionCard><StatusRow label="Push Notifications" value="Active"/><p className="text-xs text-gray-500">High-priority actions and meaningful outcomes.</p></SectionCard></div></div></Signed>;

  if (id === "s45") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="dark">SECURITY & PRIVACY</Pill><h1 className="mt-4 text-3xl font-black">Security you can understand</h1><p className="mt-2 text-sm text-gray-500">Manage sessions, permissions, devices, and your personal Career Passport data without infrastructure jargon.</p><div className="mt-6 grid gap-4 md:grid-cols-2"><SectionCard><div className="flex gap-3"><Laptop size={22} className="text-[#2C76FF]"/><div><div className="font-black">Application Browser Sessions</div><div className="mt-2 text-sm text-gray-500">1 active private application browser.</div></div></div><SecondaryButton className="mt-5 w-full">Reset Application Browser</SecondaryButton></SectionCard><SectionCard><div className="flex gap-3"><Mail size={22} className="text-[#2C76FF]"/><div><div className="font-black">Email Permission</div><div className="mt-2 text-sm text-gray-500">Job-search Gmail connected with read-only application access.</div></div></div><SecondaryButton className="mt-5 w-full">Disconnect Gmail</SecondaryButton></SectionCard><SectionCard><div className="flex gap-3"><ShieldCheck size={22} className="text-[#2C76FF]"/><div><div className="font-black">Active Sessions</div><div className="mt-2 text-sm text-gray-500">iPhone · Safari · current session.</div></div></div><SecondaryButton className="mt-5 w-full">Sign Out All Devices</SecondaryButton></SectionCard><SectionCard><div className="flex gap-3"><LockKeyhole size={22} className="text-[#2C76FF]"/><div><div className="font-black">Personal Data</div><div className="mt-2 text-sm text-gray-500">Export or delete your Career Passport and account data.</div></div></div><div className="mt-5 grid gap-2"><SecondaryButton>Export Career Passport</SecondaryButton><SecondaryButton>Delete Account / Passport</SecondaryButton></div></SectionCard></div></div></Signed>;

  if (id === "s46") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center rounded-[24px] bg-[#0B1D33] text-xl font-black text-white">RC</div><div><h1 className="text-2xl font-black">Ramakrishna Chanda</h1><div className="mt-1 text-sm text-gray-500">OneClick member · Career Passport 96%</div></div></div><div className="mt-7 grid gap-4 md:grid-cols-2">{[["Career Passport","Manage your durable application identity","s40"],["Answer Memory","Review reusable answers and their history","s41"],["Documents","Resumes, letters, transcripts, portfolio","s43"],["Connected Services","Browser, Gmail, phone, notifications","s44"],["Security & Privacy","Sessions, permissions, devices, personal data","s45"],["OneClick Membership","See monthly value and subscription","s47"]].map(([title,detail,target])=><SectionCard key={title}><button onClick={() => ctx.go(target as ScreenId)} className="flex w-full items-center gap-3 text-left"><div className="flex-1"><div className="font-black">{title}</div><div className="mt-1 text-xs leading-5 text-gray-500">{detail}</div></div><ChevronRight size={20}/></button></SectionCard>)}</div><SectionCard className="mt-5"><div className="grid gap-2 sm:grid-cols-2"><SecondaryButton><HelpCircle className="mr-2 inline" size={17}/>Support</SecondaryButton><SecondaryButton>Privacy</SecondaryButton></div></SectionCard></div></Signed>;

  if (id === "s47") return <Signed id={id} ctx={ctx}><div className="px-4 py-6 sm:px-6 lg:px-8"><Pill tone="dark">ONECLICK MEMBERSHIP</Pill><h1 className="mt-4 text-3xl font-black">Show the work your agent removed</h1><p className="mt-2 text-sm text-gray-500">A premium subscription should continuously prove what the candidate did not have to do manually.</p><SectionCard className="mt-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-bold text-gray-500">OneClick Membership</div><div className="mt-1 text-4xl font-black">$89.99<span className="text-base text-gray-400">/month</span></div></div><Pill tone="green">ACTIVE</Pill></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-5"><Metric value="38" label="applications completed"/><Metric value="327" label="questions automated"/><Metric value="11" label="verification steps"/><Metric value="4" label="candidate interruptions"/><Metric value="9h 45m" label="estimated time saved"/></div></SectionCard><div className="mt-5 rounded-[24px] bg-[#0B1D33] p-6 text-white"><div className="text-xs font-black uppercase tracking-widest text-[#29FE29]">THIS MONTH</div><div className="mt-3 text-2xl font-black">OneClick handled 96% of repetitive application work without asking you.</div><p className="mt-3 text-sm leading-6 text-slate-300">The product gets more valuable as your Career Passport and answer memory become richer.</p></div></div></Signed>;

  return null;
}
