import { Check, Linkedin, ShieldCheck, Sparkles, UploadCloud, WandSparkles } from "lucide-react";
import type { ScreenId } from "./flow";
import { ChoiceCard, Field, PageShell, Pill, PrimaryButton, ProgressBar, SectionCard, SecondaryButton, StatusRow } from "./ui";

export interface ScreenCtx {
  go: (id: ScreenId) => void;
  next: () => void;
  back: () => void;
  state: {
    resumeUploaded: boolean;
    extractionComplete: boolean;
    gmailConnected: boolean;
    telegramConnected: boolean;
    pushEnabled: boolean;
    smsEnabled: boolean;
    telegramAnswer: "Yes" | "No" | "I'm unsure" | null;
  };
  setState: (patch: Partial<ScreenCtx["state"]>) => void;
}

const Footer = ({ ctx, primary = "Continue", secondary = "Back", onPrimary }: { ctx: ScreenCtx; primary?: string; secondary?: string; onPrimary?: () => void }) => <div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">{secondary}</SecondaryButton><PrimaryButton onClick={onPrimary ?? ctx.next} className="flex-1">{primary}</PrimaryButton></div>;

export function renderOnboardingScreen(id: ScreenId, ctx: ScreenCtx) {
  if (id === "s01") return <div className="min-h-screen bg-white lg:grid lg:grid-cols-2"><div className="flex min-h-screen flex-col justify-between p-6 sm:p-10 lg:p-16"><div className="font-black tracking-tight">APPLY WIZZ</div><div className="max-w-xl"><Pill tone="green">YOUR CAREER PARTNER</Pill><h1 className="mt-5 text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">Apply to jobs without filling the same forms again and again.</h1><p className="mt-5 text-base leading-7 text-gray-600 sm:text-lg">Build your Career Passport once. Approve the jobs you want. OneClick completes the repetitive application work for you.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><PrimaryButton onClick={() => ctx.go("s02")}>Get Started</PrimaryButton><SecondaryButton onClick={() => ctx.go("s22")}>Sign In</SecondaryButton></div></div><div className="text-xs text-gray-400">One-time setup · remembered answers · minimal interruption</div></div><div className="hidden bg-[#0B1D33] p-10 lg:flex lg:items-center"><div className="mx-auto w-full max-w-lg rounded-[32px] border border-white/10 bg-white/5 p-8 text-white shadow-2xl"><div className="text-sm font-bold text-[#29FE29]">MICROSOFT · SOFTWARE ENGINEER</div><div className="mt-6 grid grid-cols-2 gap-4"><div><div className="text-4xl font-black">93%</div><div className="text-sm text-slate-300">Job Match</div></div><div><div className="text-4xl font-black">10/10</div><div className="text-sm text-slate-300">Ready</div></div></div><div className="mt-6 rounded-2xl bg-[#29FE29] p-4 font-black text-[#0B1D33]">Apply with OneClick</div></div></div></div>;

  if (id === "s02") return <PageShell eyebrow="ACCOUNT" title="Create your account" description="Set up a secure account for your Career Passport and OneClick Agent." footer={<Footer ctx={ctx} primary="Continue"/>}><SectionCard><div className="grid gap-3"><SecondaryButton>Continue with Google</SecondaryButton><SecondaryButton>Continue with Apple</SecondaryButton><div className="my-2 flex items-center gap-3 text-xs text-gray-400"><div className="h-px flex-1 bg-gray-200"/>OR<div className="h-px flex-1 bg-gray-200"/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value="Ramakrishna"/><Field label="Last name" value="Chanda"/></div><Field label="Email" value="rama@example.com"/><Field label="Phone" value="+1 (469) 555-0142"/></div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]">Signing in with Google does not give Apply Wizz access to your Gmail. Job-search email permission is a separate choice later.</div></PageShell>;

  if (id === "s03") return <PageShell eyebrow="SECURITY" title="Verify your account" description="We use this to secure your Career Passport and notify you when an application genuinely needs your attention." footer={<Footer ctx={ctx} primary="Verify & Continue"/>}><SectionCard><Field label="Verification code" value="483291"/><div className="mt-4 text-xs text-gray-500">Sent to r••••@example.com and +1 ••• ••• 0142</div></SectionCard></PageShell>;

  if (id === "s04") return <PageShell eyebrow="CAREER PASSPORT" title="Build your Career Passport" description="Give Apply Wizz your career information once. We’ll reuse verified information whenever employers ask the same questions."><div className="space-y-4"><ChoiceCard title="Upload Resume" description="Recommended · about 2 minutes. We’ll extract your education, experience, skills, projects and more." badge={<Pill tone="green">Recommended</Pill>} selected onClick={() => ctx.go("s05")}/><ChoiceCard title="Import Professional Profile" description="Bring in an existing professional profile, including LinkedIn-style information." badge={<Linkedin size={22} className="text-[#2C76FF]"/>} onClick={() => ctx.go("s06")}/><ChoiceCard title="Build From Scratch" description="Enter your information step by step with a guided Career Passport setup." onClick={() => ctx.go("s09")}/></div><div className="mt-6"><SecondaryButton onClick={ctx.back}>Back</SecondaryButton></div></PageShell>;

  if (id === "s05") return <PageShell eyebrow="CAREER PASSPORT" title="Upload your resume" description="Your resume is used to build your Career Passport and complete applications you approve." footer={<Footer ctx={ctx} primary={ctx.state.resumeUploaded ? "Continue with this resume" : "Build My Passport"} onPrimary={() => { ctx.setState({ resumeUploaded: true }); ctx.go("s06"); }}/>}>{ctx.state.resumeUploaded ? <SectionCard><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#E9FFE9] text-[#0B6B22]"><Check size={26}/></div><div className="flex-1"><div className="font-black">Ramakrishna_Resume.pdf</div><div className="mt-1 text-sm text-gray-500">Resume saved · you won’t need to upload it again.</div></div><Pill tone="green">READY</Pill></div></SectionCard> : <SectionCard className="border-dashed border-blue-200 bg-[#EFFBFF]/40"><div className="py-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-white text-[#2C76FF] shadow-sm"><UploadCloud size={30}/></div><div className="mt-4 font-black">Drop your resume here</div><div className="mt-1 text-sm text-gray-500">PDF or DOCX · up to 10 MB</div><SecondaryButton className="mt-5" onClick={() => ctx.setState({ resumeUploaded: true })}>Browse Files</SecondaryButton></div></SectionCard>}</PageShell>;

  if (id === "s06") return <PageShell eyebrow="AI EXTRACTION" title="Building your Career Passport" description="OneClick is turning your resume into reusable application-ready information." footer={<div className="flex gap-3"><SecondaryButton onClick={() => ctx.go("s05")} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={() => { ctx.setState({ resumeUploaded: true, extractionComplete: true }); ctx.go("s07"); }} className="flex-1">Review Your Passport</PrimaryButton></div>}><SectionCard><div className="mb-5 flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><WandSparkles size={24}/></div><div><div className="font-black">Reading your resume</div><div className="text-xs text-gray-500">21 career details found</div></div></div><div className="space-y-3">{["Personal information","Education","Experience","Skills","Projects","Certifications"].map((x)=><div key={x} className="flex items-center justify-between rounded-xl bg-gray-50 px-4 py-3 text-sm font-bold"><span>{x}</span><Check size={18} className="text-[#0B6B22]"/></div>)}</div><div className="mt-5"><ProgressBar value={100} tone="green"/></div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]">Going back keeps this resume and extraction progress saved.</div></PageShell>;

  if (id === "s07") return <PageShell eyebrow="REVIEW" title="Review what we found" description="Nothing becomes trusted Career Passport data until you can review it." footer={<Footer ctx={ctx} primary="Confirm & Continue"/>}><SectionCard><div className="flex items-center justify-between"><h3 className="font-black">Personal Information</h3><button className="text-sm font-bold text-[#2C76FF]">Edit</button></div><div className="mt-3 grid gap-2 text-sm text-gray-600"><div>Ramakrishna Chanda</div><div>Dallas, TX</div><div>rama@example.com · +1 (469) 555-0142</div><div>linkedin.com/in/ramakrishna</div></div></SectionCard><SectionCard><div className="flex items-center justify-between"><h3 className="font-black">Education</h3><button className="text-sm font-bold text-[#2C76FF]">Edit</button></div><div className="mt-3 text-sm text-gray-600">MS Computer Science · University of Texas at Dallas · May 2027</div></SectionCard><SectionCard><div className="flex items-center justify-between"><h3 className="font-black">Experience & Skills</h3><button className="text-sm font-bold text-[#2C76FF]">Edit</button></div><div className="mt-3 text-sm text-gray-600">Software Engineer Intern · React · Python · AWS · Machine Learning</div></SectionCard></PageShell>;

  if (id === "s08") return <PageShell eyebrow="GAP ANALYSIS" title="Your resume gave us most of what we need" description="Answer the remaining application details once. OneClick can reuse them when employers ask." footer={<Footer ctx={ctx} primary="Complete 6 Answers"/>}><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#E9FFE9] p-4"><div className="text-3xl font-black text-[#0B6B22]">21</div><div className="text-xs font-bold text-[#0B6B22]">details ready</div></div><div className="rounded-2xl bg-[#FFF7CC] p-4"><div className="text-3xl font-black text-[#6E5900]">6</div><div className="text-xs font-bold text-[#6E5900]">still needed</div></div></div><SectionCard>{["Work authorization","Sponsorship","Preferred locations","Relocation","Earliest start date","Compensation preference"].map((x)=><StatusRow key={x} label={x} value="Needed" positive={false}/>)}</SectionCard></PageShell>;

  if (id === "s09") return <PageShell eyebrow="CAREER PASSPORT" title="Work authorization" description="These answers are sensitive and important, so OneClick never guesses or changes them without your confirmation." footer={<Footer ctx={ctx}/>}><SectionCard><div className="font-black">Are you currently authorized to work in the United States?</div><div className="mt-4 grid grid-cols-3 gap-2">{["Yes","No","Not sure"].map((x)=><SecondaryButton key={x}>{x}</SecondaryButton>)}</div></SectionCard><SectionCard><div className="font-black">Will you now or in the future require employer sponsorship?</div><div className="mt-4 grid grid-cols-3 gap-2">{["Yes","No","Not sure"].map((x)=><SecondaryButton key={x}>{x}</SecondaryButton>)}</div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]"><ShieldCheck className="mr-2 inline" size={18}/>These become canonical Career Passport facts only after you confirm them.</div></PageShell>;

  if (id === "s10") return <PageShell eyebrow="CAREER PASSPORT" title="Help OneClick understand what is worth applying to" description="Tell us what good opportunities look like for you—not just how to filter a job board." footer={<Footer ctx={ctx}/>}><SectionCard><div className="grid gap-4 sm:grid-cols-2"><Field label="Target roles" value="Software Engineer, ML Engineer"/><Field label="Employment type" value="Full-time"/><Field label="Preferred locations" value="Seattle, Bay Area, Austin"/><Field label="Work style" value="Hybrid or Remote"/><Field label="Earliest start date" value="June 15, 2027"/><Field label="Compensation target" value="$140K+"/></div></SectionCard></PageShell>;

  if (id === "s11") return <PageShell eyebrow="ANSWER MEMORY" title="Answer common questions once" description="Employers repeatedly ask the same things. OneClick remembers your confirmed answers so you don’t have to re-enter them." footer={<Footer ctx={ctx}/>}><SectionCard>{[["Are you at least 18?","Yes"],["Are you willing to relocate?","Yes"],["Can you work onsite?","Yes"],["Earliest start date","June 15, 2027"],["Desired salary","$140K+"]].map(([a,b])=><div key={a} className="flex items-center justify-between gap-3 border-b border-gray-100 py-3 last:border-0"><div><div className="text-sm font-bold">{a}</div><div className="mt-1 text-xs text-gray-400">Reusable answer</div></div><Pill tone="green">{b}</Pill></div>)}</SectionCard></PageShell>;

  if (id === "s12") return <PageShell eyebrow="TRUST" title="Some answers always stay yours" description="OneClick will never guess sensitive answers that require your judgment or consent." footer={<Footer ctx={ctx} primary="I Understand"/>}><SectionCard><div className="grid gap-3">{["Veteran status","Disability disclosure","Demographic information","Criminal-history questions","Conflicts of interest","Legal attestations"].map((x)=><div key={x} className="rounded-xl bg-gray-50 px-4 py-3 text-sm font-bold">{x}</div>)}</div></SectionCard><div className="rounded-2xl bg-[#0B1D33] p-5 text-sm leading-6 text-white">When an employer asks a sensitive question you haven’t explicitly answered, OneClick pauses and asks you.</div></PageShell>;

  if (id === "s13") return <PageShell eyebrow="CAREER PASSPORT" title="Your Career Passport is ready" description="You’ve created a reusable professional identity. Next, activate the tools OneClick uses to take action." footer={<div className="flex gap-3"><SecondaryButton onClick={ctx.back} className="flex-1">Back</SecondaryButton><PrimaryButton onClick={ctx.next} className="flex-1">Activate OneClick</PrimaryButton></div>}><SectionCard><div className="flex items-center justify-between"><div><div className="text-xl font-black">Ramakrishna Chanda</div><div className="mt-1 text-sm text-gray-500">Career Passport</div></div><div className="text-3xl font-black text-[#2C76FF]">92%</div></div><div className="mt-5"><ProgressBar value={92}/></div><div className="mt-5">{["Personal information","Education","Experience","Skills","Work authorization","Preferences","Application answers","Resume"].map((x)=><StatusRow key={x} label={x} value="Ready"/>)}</div></SectionCard><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]"><Sparkles className="mr-2 inline" size={18}/>Career Passport = information. OneClick Agent = action.</div></PageShell>;

  return null;
}
