import { useMemo, useState } from "react";
import {
  ArrowLeft, ArrowRight, Bell, Briefcase, Check, CheckCircle2, ChevronRight,
  Clock3, FileText, Home, LockKeyhole, Mail, MapPin, Menu, MessageSquare,
  MoreHorizontal, ShieldCheck, Sparkles, Upload, UserRound, WalletCards,
  CircleAlert, CircleHelp, GraduationCap, Building2, CalendarDays, Search,
  SlidersHorizontal, X, RotateCcw, Eye, Settings, LogOut, Smartphone
} from "lucide-react";

type Screen =
  | "welcome" | "signup" | "verify" | "passport-intro" | "passport"
  | "resume" | "passport-ready" | "home" | "jobs" | "job-detail"
  | "readiness" | "missing" | "confirm" | "ready" | "otp-availability"
  | "progress" | "otp" | "new-question" | "human" | "login-required"
  | "submitted" | "applications" | "need-action" | "application-detail" | "profile";

type AppStatus = "ready" | "running" | "waiting_for_otp" | "one_answer_needed" | "human_verification" | "login_needed" | "completed";

const jobs = [
  { id: "ms", company: "Microsoft", role: "Software Engineer", location: "Redmond, WA", salary: "$140K–$175K", match: 93, readiness: "8/10", tag: "Strong match", accent: "#2C76FF" },
  { id: "gg", company: "Google", role: "Software Engineer", location: "Mountain View, CA", salary: "$155K–$190K", match: 95, readiness: "10/10", tag: "Ready to apply", accent: "#29FE29" },
  { id: "nv", company: "NVIDIA", role: "ML Engineer", location: "Santa Clara, CA", salary: "$150K–$205K", match: 92, readiness: "9/10", tag: "Verification likely", accent: "#FFDE59" },
  { id: "am", company: "Amazon", role: "SDE Intern", location: "Seattle, WA", salary: "$48–$62/hr", match: 88, readiness: "9/10", tag: "1 answer needed", accent: "#FFDE59" },
];

const brand = {
  black: "#1E1E1E", green: "#29FE29", blue: "#2C76FF", soft: "#F5F5F5",
  tint: "#EFFBFF", navy: "#0B1D33", yellow: "#FFDE59", coral: "#FF5C5C"
};

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-2.5 font-black tracking-tight text-[#1E1E1E]">
    <div className="grid h-9 w-9 place-items-center rounded-xl bg-[#1E1E1E] text-sm font-black text-white">AW</div>
    {!compact && <span className="text-lg">APPLY WIZZ</span>}
  </div>;
}

function Pill({ children, tone = "blue" }: { children: React.ReactNode; tone?: "blue" | "green" | "yellow" | "red" | "gray" }) {
  const c = tone === "green" ? "bg-[#E9FFE9] text-[#0B6B22]" : tone === "yellow" ? "bg-[#FFF8D5] text-[#735E00]" : tone === "red" ? "bg-[#FFF0F0] text-[#B42318]" : tone === "gray" ? "bg-gray-100 text-gray-700" : "bg-[#EFFBFF] text-[#185BCC]";
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-bold ${c}`}>{children}</span>;
}

function Button({ children, onClick, variant = "primary", disabled = false, className = "" }: { children: React.ReactNode; onClick?: () => void; variant?: "primary" | "secondary" | "dark" | "danger"; disabled?: boolean; className?: string }) {
  const styles = variant === "secondary" ? "border border-gray-200 bg-white text-[#1E1E1E] hover:bg-gray-50" : variant === "dark" ? "bg-[#0B1D33] text-white hover:bg-[#142942]" : variant === "danger" ? "bg-[#FF5C5C] text-white" : "bg-[#2C76FF] text-white hover:bg-[#1E67EE]";
  return <button disabled={disabled} onClick={onClick} className={`min-h-11 rounded-2xl px-5 py-3 text-sm font-extrabold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles} ${className}`}>{children}</button>;
}

function Field({ label, placeholder, value }: { label: string; placeholder?: string; value?: string }) {
  return <label className="block"><span className="mb-2 block text-sm font-bold text-gray-800">{label}</span><input defaultValue={value} placeholder={placeholder} className="min-h-12 w-full rounded-2xl border border-gray-200 bg-white px-4 text-sm outline-none transition focus:border-[#2C76FF] focus:ring-4 focus:ring-blue-50" /></label>;
}

function ScoreRing({ score }: { score: number }) {
  const deg = score * 3.6;
  return <div className="relative grid h-28 w-28 place-items-center rounded-full" style={{ background: `conic-gradient(${brand.blue} ${deg}deg,#E9EEF5 0deg)` }}>
    <div className="grid h-20 w-20 place-items-center rounded-full bg-white"><div className="text-center"><div className="text-2xl font-black">{score}%</div><div className="text-[10px] font-bold uppercase tracking-wide text-gray-500">Match</div></div></div>
  </div>;
}

function Progress({ value, color = brand.blue }: { value: number; color?: string }) {
  return <div className="h-2.5 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full transition-all" style={{ width: `${value}%`, background: color }} /></div>;
}

function TopBar({ title, back, action }: { title?: string; back?: () => void; action?: React.ReactNode }) {
  return <div className="sticky top-0 z-20 flex min-h-16 items-center justify-between border-b border-gray-100 bg-white/95 px-4 backdrop-blur md:px-6">
    <div className="flex items-center gap-3">{back ? <button onClick={back} className="grid h-11 w-11 place-items-center rounded-xl hover:bg-gray-100"><ArrowLeft size={20} /></button> : <Logo compact />} {title && <span className="font-extrabold">{title}</span>}</div>{action || <div className="w-11" />}
  </div>;
}

function Shell({ screen, go, children }: { screen: Screen; go: (s: Screen) => void; children: React.ReactNode }) {
  const nav = [
    ["home", Home, "Home"], ["jobs", Briefcase, "Jobs"], ["applications", FileText, "Applications"], ["profile", UserRound, "Profile"]
  ] as const;
  return <div className="min-h-screen bg-[#F7F9FC] lg:flex">
    <aside className="hidden w-64 shrink-0 border-r border-gray-200 bg-white p-5 lg:flex lg:flex-col">
      <Logo />
      <nav className="mt-10 space-y-2">{nav.map(([key, Icon, label]) => <button key={key} onClick={() => go(key as Screen)} className={`flex min-h-12 w-full items-center gap-3 rounded-2xl px-4 text-sm font-bold ${screen === key ? "bg-[#EFFBFF] text-[#185BCC]" : "text-gray-600 hover:bg-gray-50"}`}><Icon size={20}/>{label}</button>)}</nav>
      <div className="mt-auto rounded-2xl bg-[#0B1D33] p-4 text-white"><div className="mb-2 flex items-center gap-2"><Sparkles size={18} className="text-[#29FE29]"/><b>Application Agent</b></div><p className="text-xs text-slate-300">Ready and monitoring your approved applications.</p></div>
    </aside>
    <main className="mx-auto min-h-screen w-full max-w-6xl pb-24 lg:pb-8">{children}</main>
    <nav className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 border-t border-gray-200 bg-white/95 px-2 py-2 backdrop-blur lg:hidden">{nav.map(([key, Icon, label]) => <button key={key} onClick={() => go(key as Screen)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-bold ${screen === key ? "text-[#2C76FF]" : "text-gray-500"}`}><Icon size={20}/>{label}</button>)}</nav>
  </div>;
}

function Welcome({ go }: { go: (s: Screen) => void }) {
  return <div className="min-h-screen bg-white lg:grid lg:grid-cols-2">
    <div className="flex min-h-screen flex-col justify-between p-6 sm:p-10 lg:p-16"><Logo/><div className="mx-auto w-full max-w-xl py-16 lg:py-0"><Pill tone="green"><Sparkles size={13}/> Your Career Partner</Pill><h1 className="mt-6 text-4xl font-black leading-tight text-[#1E1E1E] sm:text-5xl lg:text-6xl">Spend less time applying.<br/><span className="text-[#2C76FF]">More time getting ready.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-gray-600 sm:text-lg">Apply Wizz handles repetitive job applications and asks you only when your input is genuinely needed.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button onClick={() => go("signup")} className="sm:min-w-40">Get Started <ArrowRight className="ml-2 inline" size={17}/></Button><Button variant="secondary" onClick={() => go("home")}>I already have an account</Button></div></div><p className="text-xs text-gray-400">By continuing, you agree to our Terms and Privacy Policy.</p></div>
    <div className="hidden bg-[#0B1D33] p-10 text-white lg:flex lg:items-center"><div className="mx-auto w-full max-w-lg"><div className="rounded-[32px] border border-white/10 bg-white/5 p-7 shadow-2xl"><p className="text-sm font-bold text-[#29FE29]">MICROSOFT • SOFTWARE ENGINEER</p><div className="mt-5 flex items-center justify-between"><div><div className="text-4xl font-black">93%</div><div className="text-sm text-slate-300">Job match</div></div><div><div className="text-4xl font-black">8/10</div><div className="text-sm text-slate-300">Answers ready</div></div></div><div className="mt-6 rounded-2xl bg-white/10 p-4"><div className="mb-3 flex items-center justify-between text-sm"><span>Application readiness</span><b>80%</b></div><Progress value={80} color={brand.green}/></div><div className="mt-6 rounded-2xl bg-[#29FE29] p-4 font-black text-[#0B1D33]">One tap to approve. We handle the rest.</div></div></div></div>
  </div>;
}

function Signup({ go }: { go: (s: Screen) => void }) {
  return <div className="min-h-screen bg-[#F7F9FC]"><TopBar back={() => go("welcome")} /><div className="mx-auto max-w-xl px-5 py-10"><h1 className="text-3xl font-black">Create your account</h1><p className="mt-2 text-gray-500">Your application agent starts with a secure profile.</p><div className="mt-8 space-y-3"><Button variant="dark" className="w-full"> Continue with Apple</Button><Button variant="secondary" className="w-full">Continue with Google</Button><div className="flex items-center gap-3 py-2"><div className="h-px flex-1 bg-gray-200"/><span className="text-xs text-gray-400">OR</span><div className="h-px flex-1 bg-gray-200"/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" value="Ramakrishna"/><Field label="Last name" value="Chanda"/></div><Field label="Email" value="rama21@example.com"/><Field label="Phone" value="+1 (469) 555-0142"/><Button onClick={() => go("verify")} className="w-full">Continue</Button></div></div></div>;
}

function Verify({ go }: { go: (s: Screen) => void }) {
  return <div className="min-h-screen bg-white"><TopBar back={() => go("signup")} /><div className="mx-auto max-w-lg px-5 py-16 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-[#EFFBFF] text-[#2C76FF]"><Mail size={34}/></div><h1 className="mt-7 text-3xl font-black">Verify your email</h1><p className="mt-3 text-gray-500">We sent a verification link to <b className="text-gray-900">rama21@example.com</b>.</p><div className="mt-8 grid gap-3"><Button onClick={() => go("passport-intro")}>I've verified my email</Button><Button variant="secondary">Resend email</Button></div></div></div>;
}

const passportSteps = ["Basic info", "Education", "Experience", "Work authorization", "Preferences", "Common answers", "Review"];
function Passport({ go }: { go: (s: Screen) => void }) {
  const [step, setStep] = useState(0);
  const content = [
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Legal first name" value="Ramakrishna"/><Field label="Legal last name" value="Chanda"/><Field label="Phone" value="+1 (469) 555-0142"/><Field label="City" value="Dallas"/><Field label="State" value="Texas"/><Field label="LinkedIn" value="linkedin.com/in/ramakrishna"/></div>,
    <div className="grid gap-4 sm:grid-cols-2"><Field label="University" value="University of Texas at Dallas"/><Field label="Degree" value="MS Computer Science"/><Field label="Graduation" value="May 2027"/><Field label="GPA" value="3.8"/></div>,
    <div className="space-y-4"><div className="rounded-2xl border border-gray-200 bg-white p-5"><div className="flex items-center gap-3"><Building2 className="text-[#2C76FF]"/><div><b>Software Engineer Intern</b><p className="text-sm text-gray-500">Acme Labs • May 2025–Aug 2025</p></div></div></div><Button variant="secondary">+ Add Experience</Button></div>,
    <div className="space-y-4"><Question title="Authorized to work in the United States?" options={["Yes","No"]}/><Question title="Require sponsorship now or in the future?" options={["Yes","No","I'm not sure"]}/><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]"><ShieldCheck className="mr-2 inline" size={18}/>We never infer immigration answers. You control what gets submitted.</div></div>,
    <div className="space-y-4"><div><p className="mb-3 text-sm font-bold">Target roles</p><div className="flex flex-wrap gap-2">{["Software Engineer","ML Engineer","FDE","Data Engineer"].map((x,i)=><Pill key={x} tone={i<2?"blue":"gray"}>{x}</Pill>)}</div></div><Question title="Work style" options={["Remote","Hybrid","On-site"]}/><Question title="Open to relocation?" options={["Yes","No"]}/></div>,
    <div className="space-y-4"><Question title="Are you at least 18?" options={["Yes","No"]}/><Question title="Willing to travel for work?" options={["Yes","No"]}/><Field label="Earliest start date" placeholder="Select date"/></div>,
    <div className="grid gap-3 sm:grid-cols-2">{["Personal information","Education","Experience","Work authorization","Preferences","Common answers"].map(x=><div className="flex items-center justify-between rounded-2xl border bg-white p-4" key={x}><span className="font-bold">{x}</span><CheckCircle2 className="text-green-600" size={20}/></div>)}</div>
  ][step];
  return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="Career Passport" back={() => step ? setStep(step-1) : go("passport-intro")} /><div className="mx-auto max-w-3xl px-5 py-8"><div className="mb-7 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#2C76FF]">Step {step+1} of 7</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{passportSteps[step]}</h1></div><div className="text-sm font-black">{Math.round(((step+1)/7)*100)}%</div></div><Progress value={((step+1)/7)*100}/><div className="mt-8 rounded-3xl bg-white p-5 shadow-sm sm:p-7">{content}</div><div className="mt-6 flex gap-3"><Button variant="secondary" onClick={() => step ? setStep(step-1) : go("passport-intro")} className="flex-1">Back</Button><Button onClick={() => step === 6 ? go("resume") : setStep(step+1)} className="flex-1">{step === 6 ? "Continue" : "Next"}</Button></div></div></div>;
}

function Question({ title, options }: { title: string; options: string[] }) {
  const [value,setValue]=useState(options[0]);
  return <div><p className="mb-3 text-sm font-bold">{title}</p><div className="flex flex-wrap gap-2">{options.map(o=><button key={o} onClick={()=>setValue(o)} className={`min-h-11 rounded-xl border px-4 text-sm font-bold ${value===o?"border-[#2C76FF] bg-[#EFFBFF] text-[#185BCC]":"border-gray-200 bg-white"}`}>{o}</button>)}</div></div>;
}

function PassportIntro({ go }: { go:(s:Screen)=>void }) { return <div className="min-h-screen bg-white"><TopBar back={()=>go("verify")}/><div className="mx-auto max-w-2xl px-5 py-12"><Pill tone="green"><Sparkles size={13}/> Smart profile</Pill><h1 className="mt-5 text-4xl font-black">Build your Career Passport</h1><p className="mt-4 text-lg leading-7 text-gray-500">Tell Apply Wizz about yourself once. We reuse verified information whenever employers ask the same questions.</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{[[UserRound,"Profile"],[WalletCards,"Career Passport"],[Briefcase,"Applications"]].map(([Icon,label],i)=><div key={String(label)} className="rounded-3xl bg-[#F5F5F5] p-5 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#2C76FF]">{typeof Icon!=="string" && <Icon size={24}/>}</div><b className="mt-3 block">{label as string}</b>{i<2&&<ArrowRight className="mx-auto mt-2 text-gray-300"/>}</div>)}</div><Button onClick={()=>go("passport")} className="mt-8 w-full">Build My Passport</Button></div></div> }

function Resume({go}:{go:(s:Screen)=>void}) { const [uploaded,setUploaded]=useState(false); return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="Resume" back={()=>go("passport")}/><div className="mx-auto max-w-2xl px-5 py-10"><h1 className="text-3xl font-black">Add your resume</h1><p className="mt-2 text-gray-500">We'll extract details, then you approve them.</p>{!uploaded?<button onClick={()=>setUploaded(true)} className="mt-8 flex min-h-64 w-full flex-col items-center justify-center rounded-3xl border-2 border-dashed border-blue-200 bg-white p-8 text-center hover:bg-blue-50"><Upload className="text-[#2C76FF]" size={36}/><b className="mt-4">Upload PDF</b><span className="mt-1 text-sm text-gray-500">Choose from Files or drag and drop</span></button>:<div className="mt-8 space-y-4"><div className="rounded-3xl bg-white p-5"><div className="flex items-center gap-3"><FileText className="text-[#2C76FF]"/><div><b>Ramakrishna_Resume.pdf</b><p className="text-sm text-gray-500">Parsed successfully</p></div></div></div><div className="rounded-3xl bg-white p-5"><h2 className="font-black">We found these details</h2>{["University of Texas at Dallas","MS Computer Science","Graduation: May 2027","Python • Java • AWS"].map(x=><div className="mt-3 flex items-center gap-2 text-sm" key={x}><CheckCircle2 size={17} className="text-green-600"/>{x}</div>)}</div><Button onClick={()=>go("passport-ready")} className="w-full">Looks Correct</Button></div>}</div></div> }

function PassportReady({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-white"><div className="mx-auto flex min-h-screen max-w-xl flex-col items-center justify-center px-5 text-center"><div className="grid h-24 w-24 place-items-center rounded-[30px] bg-[#E9FFE9]"><CheckCircle2 size={48} className="text-green-700"/></div><h1 className="mt-7 text-4xl font-black">Your Career Passport is ready</h1><p className="mt-3 text-gray-500">Apply Wizz now knows enough to handle most common application questions.</p><div className="mt-8 w-full rounded-3xl bg-[#EFFBFF] p-5 text-left"><div className="flex justify-between"><b>Application readiness</b><b>84%</b></div><div className="mt-3"><Progress value={84}/></div></div><Button onClick={()=>go("home")} className="mt-7 w-full">Go to Home</Button></div></div> }

function HomePage({go}:{go:(s:Screen)=>void}) { return <Shell screen="home" go={go}><TopBar title="Home" action={<button onClick={()=>go("need-action")} className="relative grid h-11 w-11 place-items-center rounded-xl hover:bg-gray-100"><Bell size={20}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#FF5C5C]"/></button>}/><div className="px-4 py-6 md:px-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-gray-500">THURSDAY, AUG 14</p><h1 className="mt-1 text-3xl font-black">Hi, Ramakrishna 👋</h1></div><Pill tone="green"><Sparkles size={13}/> Agent ready</Pill></div><section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">Need Your Action</h2><button onClick={()=>go("need-action")} className="text-sm font-bold text-[#2C76FF]">View all</button></div><div className="grid gap-3 md:grid-cols-2"><ActionCard company="NVIDIA" title="Human verification" text="One quick verification is waiting." action="Continue" onClick={()=>go("human")}/><ActionCard company="Amazon" title="One answer needed" text="Your application is paused." action="Answer" onClick={()=>go("new-question")}/></div></section><section className="mt-8"><h2 className="text-lg font-black">Recommended Applications</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{jobs.slice(0,2).map(j=><JobCard key={j.id} job={j} onClick={()=>go(j.id==="ms"?"job-detail":"readiness")}/>)}</div></section><section className="mt-8 grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Recent Applications</h2><button onClick={()=>go("applications")} className="text-sm font-bold text-[#2C76FF]">See all</button></div>{[["Stripe","Backend Engineer","Applied"],["Databricks","Software Engineer","Interview"]].map(x=><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4" key={x[0]}><div><b>{x[0]}</b><p className="text-sm text-gray-500">{x[1]}</p></div><Pill tone={x[2]==="Interview"?"green":"blue"}>{x[2]}</Pill></div>)}</div><div className="rounded-3xl bg-[#0B1D33] p-5 text-white"><div className="flex items-center justify-between"><b>Career Passport</b><span className="text-[#29FE29] font-black">94%</span></div><div className="mt-4"><Progress value={94} color={brand.green}/></div><p className="mt-4 text-sm text-slate-300">Your answers are getting more complete with every application.</p><button onClick={()=>go("profile")} className="mt-5 text-sm font-bold text-[#29FE29]">Review passport →</button></div></section></div></Shell> }

function ActionCard({company,title,text,action,onClick}:{company:string;title:string;text:string;action:string;onClick:()=>void}) { return <div className="rounded-3xl border border-yellow-200 bg-[#FFFDF2] p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#735E00]">{company}</p><h3 className="mt-1 font-black">{title}</h3><p className="mt-1 text-sm text-gray-600">{text}</p></div><Clock3 size={20} className="text-[#9A7B00]"/></div><Button onClick={onClick} variant="secondary" className="mt-4 w-full">{action}</Button></div> }

function JobCard({job,onClick}:{job:(typeof jobs)[0];onClick:()=>void}) { return <button onClick={onClick} className="group rounded-3xl bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#F5F5F5] font-black text-[#1E1E1E]">{job.company.slice(0,1)}</div><div className="text-right"><div className="text-2xl font-black text-[#2C76FF]">{job.match}%</div><div className="text-[10px] font-bold text-gray-400">MATCH</div></div></div><h3 className="mt-4 text-lg font-black">{job.role}</h3><p className="text-sm font-bold text-gray-600">{job.company}</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-gray-500"><span className="flex items-center gap-1"><MapPin size={13}/>{job.location}</span><span>•</span><span>{job.salary}</span></div><div className="mt-4 flex items-center justify-between"><Pill tone={job.tag.includes("Ready")?"green":job.tag.includes("Verification")||job.tag.includes("answer")?"yellow":"blue"}>{job.tag}</Pill><ChevronRight className="text-gray-400 transition group-hover:translate-x-1" size={20}/></div></button> }

function JobsPage({go}:{go:(s:Screen)=>void}) { return <Shell screen="jobs" go={go}><TopBar title="Jobs"/><div className="px-4 py-6 md:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-3xl font-black">Recommended for you</h1><p className="mt-1 text-gray-500">Opportunities already checked against your Career Passport.</p></div><button className="flex min-h-11 items-center gap-2 rounded-2xl border bg-white px-4 text-sm font-bold"><SlidersHorizontal size={17}/>Filters</button></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{jobs.map(j=><JobCard key={j.id} job={j} onClick={()=>go(j.id==="ms"?"job-detail":"readiness")}/>)}</div></div></Shell> }

function JobDetail({go}:{go:(s:Screen)=>void}) { return <Shell screen="jobs" go={go}><TopBar title="Job Details" back={()=>go("jobs")}/><div className="grid gap-6 px-4 py-6 md:px-8 lg:grid-cols-[1fr_360px]"><div><Pill tone="blue">Strong match</Pill><h1 className="mt-4 text-3xl font-black sm:text-4xl">Software Engineer</h1><p className="mt-2 text-lg font-bold">Microsoft</p><div className="mt-4 flex flex-wrap gap-3 text-sm text-gray-500"><span className="flex gap-1"><MapPin size={17}/>Redmond, WA</span><span>$140K–$175K</span><span>Full-time</span></div><div className="mt-8 rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">Why this matches you</h2>{[["Skills","96%"],["Experience","89%"],["Education","100%"],["Location","100%"],["Work authorization","Compatible"]].map(([a,b])=><div className="mt-4 flex items-center justify-between border-t border-gray-100 pt-4" key={a}><span className="text-sm font-bold text-gray-600">{a}</span><span className="font-black">{b}</span></div>)}<div className="mt-5 rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]">Kubernetes experience is preferred, not required. Your core qualifications are strong.</div></div></div><div className="lg:sticky lg:top-20 lg:self-start"><div className="rounded-3xl bg-white p-6 text-center shadow-sm"><ScoreRing score={93}/><h3 className="mt-5 font-black">Application inspected</h3><p className="mt-2 text-sm text-gray-500">We found 10 employer questions. You already have 8 answers ready.</p><div className="mt-5 rounded-2xl bg-[#F5F5F5] p-4 text-left"><div className="flex justify-between text-sm"><span>Readiness</span><b>8/10</b></div><div className="mt-2"><Progress value={80}/></div></div><Button onClick={()=>go("readiness")} className="mt-5 w-full">Review Application</Button></div></div></div></Shell> }

function Readiness({go}:{go:(s:Screen)=>void}) { return <Shell screen="jobs" go={go}><TopBar title="Application Readiness" back={()=>go("job-detail")}/><div className="mx-auto max-w-3xl px-4 py-6 md:px-8"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="grid gap-6 sm:grid-cols-2"><div className="rounded-3xl bg-[#EFFBFF] p-5"><p className="text-sm font-bold text-[#185BCC]">JOB MATCH</p><div className="mt-2 text-4xl font-black">93%</div><p className="mt-2 text-sm text-gray-600">Strong fit for your skills and experience.</p></div><div className="rounded-3xl bg-[#FFF8D5] p-5"><p className="text-sm font-bold text-[#735E00]">APPLICATION READINESS</p><div className="mt-2 text-4xl font-black">8/10</div><p className="mt-2 text-sm text-gray-600">Only 2 answers are missing.</p></div></div><div className="mt-7 space-y-3">{[["Profile information","Ready"],["Resume","Ready"],["Work authorization","Ready"],["Employer questions","8 of 10 ready"],["Verification","May be required"]].map(([a,b],i)=><div className="flex items-center justify-between rounded-2xl border border-gray-100 p-4" key={a}><span className="text-sm font-bold">{a}</span><Pill tone={i===4?"yellow":i===3?"blue":"green"}>{b}</Pill></div>)}</div><div className="mt-7 rounded-2xl bg-[#F5F5F5] p-4 text-sm text-gray-600"><ShieldCheck className="mr-2 inline text-[#2C76FF]" size={18}/>Tapping Apply authorizes Apply Wizz to complete this specific application using your verified information.</div><Button onClick={()=>go("missing")} className="mt-5 w-full">Apply</Button></div></div></Shell> }

function Missing({go}:{go:(s:Screen)=>void}) { const [relocate,setRelocate]=useState("Yes"); const [date,setDate]=useState("June 15, 2027"); return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="2 answers needed" back={()=>go("readiness")}/><div className="mx-auto max-w-2xl px-4 py-8"><p className="mb-6 text-gray-500">Everything else is ready. Answer these once and we'll remember them for future applications.</p><div className="space-y-5"><div className="rounded-3xl bg-white p-5"><p className="text-sm font-black">1. Are you willing to relocate to Seattle, WA?</p><div className="mt-4 flex gap-2">{["Yes","No"].map(x=><button onClick={()=>setRelocate(x)} key={x} className={`min-h-11 flex-1 rounded-2xl border font-bold ${relocate===x?"border-[#2C76FF] bg-[#EFFBFF] text-[#185BCC]":"border-gray-200"}`}>{x}</button>)}</div></div><div className="rounded-3xl bg-white p-5"><p className="text-sm font-black">2. What is your earliest available start date?</p><input value={date} onChange={e=>setDate(e.target.value)} className="mt-4 min-h-12 w-full rounded-2xl border border-gray-200 px-4"/></div></div><Button onClick={()=>go("confirm")} className="mt-6 w-full">Save Answers</Button></div></div> }

function Confirm({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-white"><TopBar title="Quick check" back={()=>go("missing")}/><div className="mx-auto max-w-lg px-5 py-16 text-center"><Pill tone="blue">1-second confirmation</Pill><h1 className="mt-5 text-3xl font-black">Your age is currently</h1><div className="mt-4 text-7xl font-black text-[#2C76FF]">28</div><p className="mt-3 text-gray-500">Is this correct?</p><div className="mt-8 grid grid-cols-2 gap-3"><Button variant="secondary">Edit</Button><Button onClick={()=>go("ready")}>Yes</Button></div></div></div> }

function Ready({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="Ready to Apply" back={()=>go("confirm")}/><div className="mx-auto max-w-xl px-5 py-10"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-black">Microsoft</p><h1 className="text-2xl font-black">Software Engineer</h1></div><Pill tone="green">10/10 Ready</Pill></div><div className="mt-6 space-y-3">{["Profile ready","Resume ready","All answers ready","Eligibility checked"].map(x=><div className="flex items-center gap-3 rounded-2xl bg-[#F5F5F5] p-4 text-sm font-bold" key={x}><CheckCircle2 size={19} className="text-green-700"/>{x}</div>)}</div><div className="mt-6 rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]">You've already authorized this application. Next we only check whether you're available in case the employer asks for verification.</div><Button onClick={()=>go("otp-availability")} className="mt-5 w-full">Continue</Button></div></div></div> }

function OTPAvailability({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-white"><TopBar title="One quick check" back={()=>go("ready")}/><div className="mx-auto max-w-lg px-5 py-16 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-[#EFFBFF] text-[#2C76FF]"><ShieldCheck size={36}/></div><h1 className="mt-6 text-3xl font-black">Are you available for verification?</h1><p className="mt-3 leading-6 text-gray-500">This application may require an email OTP or quick human action. We'll contact you only if needed.</p><div className="mt-8 grid gap-3"><Button onClick={()=>go("progress")}>Yes, I'm Available</Button><Button variant="secondary">Apply Later</Button></div></div></div> }

function ProgressPage({go}:{go:(s:Screen)=>void}) { const [stage,setStage]=useState<AppStatus>("running"); const steps = ["Application opened","Profile completed","Resume uploaded","Answering questions","Reviewing","Submitting"]; return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="Applying" back={()=>go("home")}/><div className="mx-auto max-w-2xl px-5 py-8"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-gray-500">MICROSOFT</p><h1 className="mt-1 text-2xl font-black">Software Engineer</h1></div><Pill tone="blue"><span className="h-2 w-2 animate-pulse rounded-full bg-[#2C76FF]"/>Applying</Pill></div><p className="mt-3 text-sm text-gray-500">You can close the app. We'll notify you if we need anything.</p><div className="mt-7 space-y-4">{steps.map((x,i)=><div className="flex items-center gap-4" key={x}><div className={`grid h-9 w-9 place-items-center rounded-full ${i<3?"bg-[#E9FFE9] text-green-700":i===3?"bg-[#EFFBFF] text-[#2C76FF]":"bg-gray-100 text-gray-400"}`}>{i<3?<Check size={17}/>:i+1}</div><span className={`text-sm font-bold ${i>3?"text-gray-400":""}`}>{x}</span></div>)}</div></div><div className="mt-6 rounded-3xl border border-dashed border-gray-300 bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-gray-400">Prototype controls</p><p className="mt-1 text-sm text-gray-500">Choose a simulated employer interruption.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button variant="secondary" onClick={()=>go("otp")}>Simulate OTP</Button><Button variant="secondary" onClick={()=>go("new-question")}>New Question</Button><Button variant="secondary" onClick={()=>go("human")}>Human Verification</Button><Button variant="secondary" onClick={()=>go("login-required")}>Login Required</Button></div><Button onClick={()=>go("submitted")} className="mt-3 w-full">No interruption → Submit</Button></div></div></div> }

function OTP({go}:{go:(s:Screen)=>void}) { const [code,setCode]=useState(""); const [expired,setExpired]=useState(false); return <div className="min-h-screen bg-white"><TopBar title="Verification needed" back={()=>go("progress")}/><div className="mx-auto max-w-lg px-5 py-12 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-[#FFF8D5] text-[#8A6D00]"><LockKeyhole size={34}/></div><h1 className="mt-6 text-3xl font-black">Enter your verification code</h1><p className="mt-3 text-gray-500">Microsoft sent a code to <b>ra•••••@gmail.com</b>.</p>{expired?<div className="mt-7 rounded-2xl bg-[#FFF0F0] p-5 text-left"><div className="flex gap-3"><CircleAlert className="text-[#FF5C5C]"/><div><b>That code expired</b><p className="mt-1 text-sm text-gray-500">We can request a new verification code.</p></div></div><Button onClick={()=>{setExpired(false);setCode("")}} className="mt-4 w-full">Send New Code</Button></div>:<><input maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="483291" className="mt-8 min-h-16 w-full rounded-3xl border-2 border-gray-200 text-center text-3xl font-black tracking-[.35em] outline-none focus:border-[#2C76FF]"/><Button disabled={code.length!==6} onClick={()=>go("submitted")} className="mt-4 w-full">Submit Code</Button><div className="mt-4 flex justify-center gap-4 text-sm font-bold text-[#2C76FF]"><button onClick={()=>setExpired(true)}>Simulate expired code</button><button>Resend</button></div></>}</div></div> }

function NewQuestion({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="One answer needed" back={()=>go("progress")}/><div className="mx-auto max-w-xl px-5 py-10"><div className="rounded-3xl bg-white p-6 shadow-sm"><Pill tone="yellow">Application paused</Pill><h1 className="mt-4 text-2xl font-black">We need one answer to continue</h1><p className="mt-2 text-sm text-gray-500">Microsoft • Software Engineer</p><div className="mt-7"><Question title="Have you previously interviewed with Microsoft?" options={["Yes","No","I'm not sure"]}/></div><Button onClick={()=>go("submitted")} className="mt-7 w-full">Continue Application</Button></div></div></div> }

function HumanVerification({go}:{go:(s:Screen)=>void}) { const [done,setDone]=useState(false); return <div className="min-h-screen bg-[#F7F9FC]"><TopBar title="Human verification" back={()=>go("progress")}/><div className="mx-auto max-w-2xl px-5 py-8"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#EFFBFF] text-[#2C76FF]"><Smartphone size={24}/></div><div><h1 className="text-2xl font-black">One quick verification</h1><p className="mt-2 text-sm leading-6 text-gray-500">The employer requires you to complete a human verification step. Apply Wizz does not bypass it.</p></div></div><div className="mt-7 overflow-hidden rounded-3xl border border-gray-200 bg-[#0B1D33]"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3 text-white"><span className="text-sm font-bold">Secure application session</span><ShieldCheck size={18} className="text-[#29FE29]"/></div><div className="grid min-h-64 place-items-center p-8 text-center text-white">{done?<div><CheckCircle2 className="mx-auto text-[#29FE29]" size={52}/><h3 className="mt-4 text-xl font-black">Verification complete</h3><p className="mt-2 text-sm text-slate-300">Apply Wizz is continuing your application.</p></div>:<div><CircleHelp className="mx-auto text-[#FFDE59]" size={44}/><h3 className="mt-4 text-xl font-black">Employer verification placeholder</h3><p className="mt-2 text-sm text-slate-300">In production, the user's secure interactive browser view appears here.</p><Button onClick={()=>setDone(true)} className="mt-5">Complete Demo Verification</Button></div>}</div></div>{done&&<Button onClick={()=>go("submitted")} className="mt-5 w-full">Continue</Button>}</div></div></div> }

function LoginRequired({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-white"><TopBar title="Account setup" back={()=>go("progress")}/><div className="mx-auto max-w-lg px-5 py-12"><Pill tone="blue">One-time setup</Pill><h1 className="mt-4 text-3xl font-black">This employer requires an application account</h1><p className="mt-3 text-gray-500">We'll reuse the relevant session where possible for future applications.</p><div className="mt-8 space-y-4"><Field label="Email" value="rama21@example.com"/><Field label="Password" placeholder="••••••••"/><div className="rounded-2xl bg-[#EFFBFF] p-4 text-sm text-[#185BCC]"><ShieldCheck className="mr-2 inline" size={17}/>Credentials and sessions are isolated for this employer in the production architecture.</div><Button onClick={()=>go("submitted")} className="w-full">Continue Setup & Resume</Button></div></div></div> }

function Submitted({go}:{go:(s:Screen)=>void}) { return <div className="min-h-screen bg-white"><div className="mx-auto flex min-h-screen max-w-xl flex-col items-center justify-center px-5 py-12 text-center"><div className="grid h-24 w-24 place-items-center rounded-[30px] bg-[#E9FFE9] text-green-700"><CheckCircle2 size={52}/></div><Pill tone="green"><Check size={13}/> Submitted</Pill><h1 className="mt-5 text-4xl font-black">Application submitted!</h1><p className="mt-3 text-gray-500">Microsoft • Software Engineer • Redmond, WA</p><div className="mt-8 grid w-full grid-cols-3 gap-3"><Metric value="93%" label="Match"/><Metric value="10/10" label="Ready"/><Metric value="2" label="Your actions"/></div><div className="mt-4 w-full rounded-2xl bg-[#F5F5F5] p-4 text-sm text-gray-500">Submitted Aug 14, 2026 • 10:42 PM</div><div className="mt-6 grid w-full gap-3 sm:grid-cols-2"><Button onClick={()=>go("application-detail")} variant="secondary">View Application</Button><Button onClick={()=>go("home")}>Back to Home</Button></div></div></div> }

function Metric({value,label}:{value:string;label:string}) { return <div className="rounded-2xl bg-[#F5F5F5] p-4"><div className="text-xl font-black">{value}</div><div className="mt-1 text-[11px] font-bold text-gray-500">{label}</div></div> }

function Applications({go}:{go:(s:Screen)=>void}) { const [tab,setTab]=useState("All"); const tabs=["All","In Progress","Applied","Interviews","Offers"]; return <Shell screen="applications" go={go}><TopBar title="Applications"/><div className="px-4 py-6 md:px-8"><h1 className="text-3xl font-black">Your applications</h1><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{tabs.map(t=><button onClick={()=>setTab(t)} key={t} className={`min-h-10 whitespace-nowrap rounded-full px-4 text-sm font-bold ${tab===t?"bg-[#1E1E1E] text-white":"bg-white text-gray-600"}`}>{t}</button>)}</div><div className="mt-5 space-y-3">{[["Microsoft","Software Engineer","Submitted","93%"],["NVIDIA","ML Engineer","Needs action","92%"],["Amazon","SDE Intern","One answer needed","88%"],["Databricks","Software Engineer","Interview","90%"]].map(([c,r,s,m])=><button onClick={()=>go("application-detail")} key={c} className="flex w-full items-center justify-between rounded-3xl bg-white p-5 text-left shadow-sm"><div><div className="flex items-center gap-2"><b>{c}</b><Pill tone={s==="Submitted"||s==="Interview"?"green":"yellow"}>{s}</Pill></div><p className="mt-1 text-sm text-gray-500">{r}</p></div><div className="text-right"><div className="font-black text-[#2C76FF]">{m}</div><ChevronRight className="ml-auto mt-2 text-gray-400" size={18}/></div></button>)}</div></div></Shell> }

function NeedAction({go}:{go:(s:Screen)=>void}) { return <Shell screen="home" go={go}><TopBar title="Need Your Action" back={()=>go("home")}/><div className="px-4 py-6 md:px-8"><div className="mx-auto max-w-3xl"><h1 className="text-3xl font-black">2 things need you</h1><p className="mt-2 text-gray-500">We only interrupt when your input is genuinely required.</p><div className="mt-6 space-y-4"><ActionCard company="NVIDIA" title="Human verification" text="Your ML Engineer application is waiting for a quick human step." action="Complete Verification" onClick={()=>go("human")}/><ActionCard company="Amazon" title="One answer needed" text="Your SDE Intern application needs one employer-specific answer." action="Answer Question" onClick={()=>go("new-question")}/></div></div></div></Shell> }

function ApplicationDetail({go}:{go:(s:Screen)=>void}) { const events=["Job received","Application inspected","You approved application","2 missing answers completed","Verification completed","Application submitted"]; return <Shell screen="applications" go={go}><TopBar title="Application Details" back={()=>go("applications")}/><div className="grid gap-6 px-4 py-6 md:px-8 lg:grid-cols-[1fr_340px]"><div className="rounded-3xl bg-white p-6 shadow-sm"><Pill tone="green">Submitted</Pill><h1 className="mt-4 text-3xl font-black">Software Engineer</h1><p className="mt-1 font-bold text-gray-600">Microsoft • Redmond, WA</p><div className="mt-8 space-y-5">{events.map((e,i)=><div className="flex gap-4" key={e}><div className="relative"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#E9FFE9] text-green-700"><Check size={16}/></div>{i<events.length-1&&<div className="absolute left-1/2 top-9 h-6 w-px -translate-x-1/2 bg-gray-200"/>}</div><div><b className="text-sm">{e}</b><p className="mt-1 text-xs text-gray-400">Aug 14, 2026</p></div></div>)}</div></div><div className="space-y-4"><div className="rounded-3xl bg-[#0B1D33] p-5 text-white"><div className="text-4xl font-black">93%</div><p className="text-sm text-slate-300">Match score</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><b>Application summary</b>{[["Answers used","10"],["Candidate actions","2"],["Resume","Ramakrishna_Resume.pdf"]].map(([a,b])=><div className="mt-4 flex justify-between border-t pt-4 text-sm" key={a}><span className="text-gray-500">{a}</span><b>{b}</b></div>)}</div></div></div></Shell> }

function Profile({go}:{go:(s:Screen)=>void}) { const [section,setSection]=useState("Career Passport"); const sections=["Career Passport","Answer Memory","Documents","Security","Settings"]; return <Shell screen="profile" go={go}><TopBar title="Profile"/><div className="grid gap-6 px-4 py-6 md:px-8 lg:grid-cols-[260px_1fr]"><div className="rounded-3xl bg-white p-4 shadow-sm lg:self-start"><div className="flex items-center gap-3 p-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#EFFBFF] font-black text-[#2C76FF]">RC</div><div><b>Ramakrishna</b><p className="text-xs text-gray-500">94% Passport</p></div></div><div className="mt-3 space-y-1">{sections.map(s=><button onClick={()=>setSection(s)} key={s} className={`min-h-11 w-full rounded-xl px-3 text-left text-sm font-bold ${section===s?"bg-[#EFFBFF] text-[#185BCC]":"text-gray-600"}`}>{s}</button>)}</div></div><div className="rounded-3xl bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><h1 className="text-2xl font-black">{section}</h1><Pill tone="green">94% complete</Pill></div>{section==="Career Passport"&&<div className="mt-6 grid gap-3 sm:grid-cols-2">{["Personal Information","Education","Experience","Work Authorization","Job Preferences","Application Answers"].map(x=><div className="flex items-center justify-between rounded-2xl border p-4" key={x}><b className="text-sm">{x}</b><CheckCircle2 size={19} className="text-green-600"/></div>)}</div>}{section==="Answer Memory"&&<div className="mt-6 space-y-3">{[["Willing to relocate","Yes","Used in 7 applications"],["Earliest start date","June 15, 2027","Used in 3 applications"],["Willing to travel","Yes","Used in 4 applications"]].map(([a,b,c])=><div className="rounded-2xl border p-4" key={a}><div className="flex items-center justify-between"><div><b>{a}</b><p className="mt-1 text-sm text-gray-500">{b}</p></div><button className="text-sm font-bold text-[#2C76FF]">Edit</button></div><p className="mt-3 text-xs text-gray-400">{c}</p></div>)}</div>}{section==="Documents"&&<div className="mt-6 rounded-2xl border p-5"><div className="flex items-center gap-3"><FileText className="text-[#2C76FF]"/><div><b>Ramakrishna_Resume.pdf</b><p className="text-sm text-gray-500">Primary resume • Verified</p></div></div></div>}{section==="Security"&&<div className="mt-6 space-y-3">{["Application Browser Sessions","Connected Accounts","Two-Factor Authentication","Download My Data","Delete Account"].map(x=><button key={x} className="flex min-h-12 w-full items-center justify-between rounded-2xl border px-4 text-left text-sm font-bold">{x}<ChevronRight size={18}/></button>)}</div>}{section==="Settings"&&<div className="mt-6 space-y-3">{["Notifications","Privacy","Support","Terms & Policies","Sign Out"].map(x=><button key={x} className="flex min-h-12 w-full items-center justify-between rounded-2xl border px-4 text-left text-sm font-bold">{x}<ChevronRight size={18}/></button>)}</div>}</div></div></Shell> }

export default function OneClickPrototype() {
  const [screen,setScreen]=useState<Screen>("welcome");
  const go=(s:Screen)=>{window.scrollTo({top:0,behavior:"smooth"});setScreen(s)};
  const screens:Record<Screen,React.ReactNode> = {
    welcome:<Welcome go={go}/>, signup:<Signup go={go}/>, verify:<Verify go={go}/>, "passport-intro":<PassportIntro go={go}/>, passport:<Passport go={go}/>, resume:<Resume go={go}/>, "passport-ready":<PassportReady go={go}/>, home:<HomePage go={go}/>, jobs:<JobsPage go={go}/>, "job-detail":<JobDetail go={go}/>, readiness:<Readiness go={go}/>, missing:<Missing go={go}/>, confirm:<Confirm go={go}/>, ready:<Ready go={go}/>, "otp-availability":<OTPAvailability go={go}/>, progress:<ProgressPage go={go}/>, otp:<OTP go={go}/>, "new-question":<NewQuestion go={go}/>, human:<HumanVerification go={go}/>, "login-required":<LoginRequired go={go}/>, submitted:<Submitted go={go}/>, applications:<Applications go={go}/>, "need-action":<NeedAction go={go}/>, "application-detail":<ApplicationDetail go={go}/>, profile:<Profile go={go}/>
  };
  return screens[screen];
}
